-- sudo -u postgres psql
-- \connect your_database_name
-- \dt
-- SELECT * FROM table_name;



-- CREATE DATABASE bendiks;

-- и запустить скрипт командой: 
-- psql -d bendiks -f create_base.sql

CREATE TABLE main_table (
    id SERIAL PRIMARY KEY,
    stand1_cpu VARCHAR(255),
    stand1_ram VARCHAR(255),
    stand2_cpu VARCHAR(255),
    stand2_ram VARCHAR(255),
    stand3_cpu VARCHAR(255),
    stand3_ram VARCHAR(255),
    stand4_cpu VARCHAR(255),
    stand4_ram VARCHAR(255)
);


ALTER TABLE main_table 
ADD COLUMN stand10_cpu VARCHAR(255), 
ADD COLUMN stand10_ram VARCHAR(255),
ADD COLUMN stand11_cpu VARCHAR(255),
ADD COLUMN stand11_ram VARCHAR(255),
ADD COLUMN stand12_cpu VARCHAR(255),
ADD COLUMN stand12_ram VARCHAR(255),
ADD COLUMN stand1_nvme VARCHAR(255), 
ADD COLUMN stand1_sda VARCHAR(255),
ADD COLUMN stand2_nvme VARCHAR(255), 
ADD COLUMN stand2_sda VARCHAR(255),
ADD COLUMN stand3_nvme VARCHAR(255), 
ADD COLUMN stand3_sda VARCHAR(255),
ADD COLUMN stand4_nvme VARCHAR(255), 
ADD COLUMN stand4_sda VARCHAR(255),
ADD COLUMN stand10_nvme VARCHAR(255), 
ADD COLUMN stand10_sda VARCHAR(255),
ADD COLUMN stand11_nvme VARCHAR(255), 
ADD COLUMN stand11_sda VARCHAR(255),
ADD COLUMN stand12_nvme VARCHAR(255), 
ADD COLUMN stand12_sda VARCHAR(255),
ADD COLUMN stand1_temp_cpu VARCHAR(255),
ADD COLUMN stand2_temp_cpu VARCHAR(255),
ADD COLUMN stand3_temp_cpu VARCHAR(255),
ADD COLUMN stand4_temp_cpu VARCHAR(255),
ADD COLUMN stand1_cpu_user VARCHAR(255), 
ADD COLUMN stand1_cpu_system VARCHAR(255),
ADD COLUMN stand2_cpu_user VARCHAR(255), 
ADD COLUMN stand2_cpu_system VARCHAR(255),
ADD COLUMN stand3_cpu_user VARCHAR(255), 
ADD COLUMN stand3_cpu_system VARCHAR(255),
ADD COLUMN stand4_cpu_user VARCHAR(255), 
ADD COLUMN stand4_cpu_system VARCHAR(255),
ADD COLUMN stand10_cpu_user VARCHAR(255), 
ADD COLUMN stand10_cpu_system VARCHAR(255),
ADD COLUMN stand11_cpu_user VARCHAR(255), 
ADD COLUMN stand11_cpu_system VARCHAR(255),
ADD COLUMN stand12_cpu_user VARCHAR(255), 
ADD COLUMN stand12_cpu_system VARCHAR(255),
ADD COLUMN stand5_nvme VARCHAR(255), 
ADD COLUMN stand5_sda VARCHAR(255),
ADD COLUMN stand5_cpu VARCHAR(255), 
ADD COLUMN stand5_ram VARCHAR(255),
ADD COLUMN stand5_cpu_system VARCHAR(255),
ADD COLUMN stand5_cpu_user VARCHAR(255), 
ADD COLUMN stand5_temp_cpu VARCHAR(255),
ADD COLUMN stand6_nvme VARCHAR(255), 
ADD COLUMN stand6_sda VARCHAR(255),
ADD COLUMN stand6_cpu VARCHAR(255), 
ADD COLUMN stand6_ram VARCHAR(255),
ADD COLUMN stand6_cpu_system VARCHAR(255),
ADD COLUMN stand6_cpu_user VARCHAR(255), 
ADD COLUMN stand6_temp_cpu VARCHAR(255),
ADD COLUMN stand7_nvme VARCHAR(255), 
ADD COLUMN stand7_sda VARCHAR(255),
ADD COLUMN stand7_cpu VARCHAR(255), 
ADD COLUMN stand7_ram VARCHAR(255),
ADD COLUMN stand7_cpu_system VARCHAR(255),
ADD COLUMN stand7_cpu_user VARCHAR(255), 
ADD COLUMN stand7_temp_cpu VARCHAR(255),
ADD COLUMN stand8_nvme VARCHAR(255), 
ADD COLUMN stand8_sda VARCHAR(255),
ADD COLUMN stand8_cpu VARCHAR(255), 
ADD COLUMN stand8_ram VARCHAR(255),
ADD COLUMN stand8_cpu_system VARCHAR(255),
ADD COLUMN stand8_cpu_user VARCHAR(255), 
ADD COLUMN stand8_temp_cpu VARCHAR(255),
ADD COLUMN stand9_nvme VARCHAR(255), 
ADD COLUMN stand9_sda VARCHAR(255),
ADD COLUMN stand9_cpu VARCHAR(255), 
ADD COLUMN stand9_ram VARCHAR(255),
ADD COLUMN stand9_cpu_system VARCHAR(255),
ADD COLUMN stand9_cpu_user VARCHAR(255), 
ADD COLUMN stand9_temp_cpu VARCHAR(255),
ADD COLUMN stand13_nvme VARCHAR(255), 
ADD COLUMN stand13_sda VARCHAR(255),
ADD COLUMN stand13_cpu VARCHAR(255), 
ADD COLUMN stand13_ram VARCHAR(255),
ADD COLUMN stand13_cpu_system VARCHAR(255),
ADD COLUMN stand13_cpu_user VARCHAR(255), 
ADD COLUMN stand13_temp_cpu VARCHAR(255),
ADD COLUMN stand10_temp_cpu VARCHAR(255),
ADD COLUMN stand11_temp_cpu VARCHAR(255),
ADD COLUMN stand12_temp_cpu VARCHAR(255);


INSERT INTO main_table (
    stand1_cpu, stand1_ram, stand2_cpu, stand2_ram,
    stand3_cpu, stand3_ram, stand4_cpu, stand4_ram,
    stand10_cpu, stand10_ram, stand11_cpu, stand11_ram,
    stand12_cpu, stand12_ram, stand1_nvme, stand1_sda,
    stand2_nvme, stand2_sda, stand3_nvme, stand3_sda,
    stand4_nvme, stand4_sda, stand10_nvme, stand10_sda,
    stand11_nvme, stand11_sda, stand12_nvme, stand12_sda,
    stand1_temp_cpu, stand2_temp_cpu, stand3_temp_cpu, stand4_temp_cpu,
    stand1_cpu_user, stand1_cpu_system, stand2_cpu_user, stand2_cpu_system,
    stand3_cpu_user, stand3_cpu_system, stand4_cpu_user, stand4_cpu_system,
    stand10_cpu_user, stand10_cpu_system, stand11_cpu_user, stand11_cpu_system,
    stand12_cpu_user, stand12_cpu_system, stand5_nvme, stand5_sda,
    stand5_cpu, stand5_ram, stand5_cpu_system, stand5_cpu_user, stand5_temp_cpu,
    stand6_nvme, stand6_sda, stand6_cpu, stand6_ram,
    stand6_cpu_system, stand6_cpu_user, stand6_temp_cpu,
    stand7_nvme, stand7_sda, stand7_cpu, stand7_ram,
    stand7_cpu_system, stand7_cpu_user, stand7_temp_cpu,
    stand8_nvme, stand8_sda, stand8_cpu, stand8_ram,
    stand8_cpu_system, stand8_cpu_user, stand8_temp_cpu,
    stand9_nvme, stand9_sda, stand9_cpu, stand9_ram,
    stand9_cpu_system, stand9_cpu_user, stand9_temp_cpu,
    stand13_nvme, stand13_sda, stand13_cpu, stand13_ram,
    stand13_cpu_system, stand13_cpu_user, stand13_temp_cpu,
    stand10_temp_cpu, stand11_temp_cpu, stand12_temp_cpu
) VALUES (
    '1_cpu', '1_ram', '2_cpu', '2_ram',
    '3_cpu', '3_ram', '4_cpu', '4_ram',
    '10_cpu', '10_ram', '11_cpu', '11_ram',
    '12_cpu', '12_ram', '1_nvme', '1_sda',
    '2_nvme', '2_sda', '3_nvme', '3_sda',
    '4_nvme', '4_sda', '10_nvme', '10_sda',
    '11_nvme', '11_sda', '12_nvme', '12_sda',
    '1_temp_cpu', '2_temp_cpu', '3_temp_cpu', '4_temp_cpu',
    '1_cpu_user', '1_cpu_system', '2_cpu_user', '2_cpu_system',
    '3_cpu_user', '3_cpu_system', '4_cpu_user', '4_cpu_system',
    '10_cpu_user', '10_cpu_system', '11_cpu_user', '11_cpu_system',
    '12_cpu_user', '12_cpu_system', '5_nvme', '5_sda',
    '5_cpu', '5_ram', '5_cpu_system', '5_cpu_user', '5_temp_cpu',
    '6_nvme', '6_sda', '6_cpu', '6_ram',
    '6_cpu_system', '6_cpu_user', '6_temp_cpu',
    '7_nvme', '7_sda', '7_cpu', '7_ram',
    '7_cpu_system', '7_cpu_user', '7_temp_cpu',
    '8_nvme', '8_sda', '8_cpu', '8_ram',
    '8_cpu_system', '8_cpu_user', '8_temp_cpu',
    '9_nvme', '9_sda', '9_cpu', '9_ram',
    '9_cpu_system', '9_cpu_user', '9_temp_cpu',
    '13_nvme', '13_sda', '13_cpu', '13_ram',
    '13_cpu_system', '13_cpu_user', '13_temp_cpu',
    '10_temp_cpu', '11_temp_cpu', '12_temp_cpu'
);

