FROM python:3.12-slim

WORKDIR /git

# Установка devpi-server, devpi-web (для веб-интерфейса) и devpi-client
RUN pip install --no-cache-dir devpi-server devpi-web devpi-client
RUN apt update && apt install git -y

# Открываем порт 3141 (используется как для API, так и для веб-интерфейса)
EXPOSE 3141

# Создаем директорию для данных
RUN mkdir -p /data

# Инициализация devpi-сервера
RUN devpi-init --serverdir /data --root-passwd=pass_adm

# Устанавливаем переменную окружения для использования devpi-client
ENV DEVPISERVER_SERVERDIR=/data

# Запускаем devpi-сервер в фоне, проводим начальную настройку и завершаем его
RUN (devpi-server --host 0.0.0.0 --port 3141 --serverdir /data &) && \
    sleep 15 && \
    devpi use http://localhost:3141 && \
    devpi login root --password=pass_adm && \
    devpi index -c release bases=root/pypi && \
    devpi user -c test_n password=test_p && \
    devpi login test_n --password=test_p && \
    devpi index -c dev bases=root/pypi
RUN kill -TERM 1

COPY ./auto_check_new_version/new_release.py /git/

# При старте контейнера запускается devpi-сервер с включенным веб-интерфейсом (доступным по http://localhost:3141)
CMD ["sh", "-c", "(devpi-server --host 0.0.0.0 --port 3141 --serverdir /data &) && python3 new_release.py"]

