#!/bin/bash
set -e
chmod +x /usr/bin/allta-vm
chmod +x /opt/allta_vm/vm/base_network.sh
chmod +x /opt/allta_vm/vm/network.sh
chmod +x /opt/allta_vm/vm/provision.sh
chmod 775 -R /opt/allta_vm/
mkdir /opt/allta_vm/jobs
chmod 775 -R /opt/allta_vm/jobs
chmod 775 -R /opt/allta_vm/vm
exit 0
