FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      ssh \
      sshpass \
      curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /server

RUN pip install --upgrade pip
RUN pip install poetry

COPY . .

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
RUN mkdir /data
EXPOSE 8000

CMD ["gunicorn", "--config", "gunicorn_conf.py", "app.main:app"]
