FROM python:3.12-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /celery

RUN pip install --upgrade pip
RUN pip install poetry

COPY . .

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

EXPOSE 8000

WORKDIR /celery

# Запуск Celery worker
CMD ["celery", "-A", "celery_app:app", "worker", "-n" ,"worker@allta-vm",  "--loglevel=info"]
