Vagrant.configure("2") do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'libvirt'
 

  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.box = ENV['UPDATE']

  VM_MEMORY = 8192
  VM_CPUS   = 5

  vpn_nodes = [
    { name: "vpn1",   hostname: "vpn1.stress.rbt", ip: "192.168.50.121" },
    { name: "pooler", hostname: "pooler.stress.rbt", ip: "dhcp" }
  ]

  vpn_nodes.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.hostname = vm[:hostname]

      # Убираем дефолтную сеть vagrant-libvirt
      node.vm.provider :libvirt do |v|
        v.driver = "kvm"
        v.uri = "qemu:///system"
        v.memory = VM_MEMORY
        v.cpus = VM_CPUS
        v.disk_bus = "sata"
        v.management_network_name = "none"
        v.management_network_device = "eth999"
      end

      # Прописка провижена
      node.vm.provision "shell",
        privileged: true,
        path: "provision/vagrant_user.sh"
    end
  end
end

