FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    nginx \
    && apt-get clean

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /app

# Удаляем конфликты, если они были
RUN rm -rf /etc/nginx/sites-enabled/default

COPY ./nginx-config/web-app.conf /etc/nginx/sites-enabled/web-app.conf

# Даем права на логи
RUN mkdir -p /var/log/nginx
RUN chown -R www-data:www-data /var/log/nginx

EXPOSE 80

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "--chdir", "/app/web_app", "wsgi:application"]



