Vagrant.configure("2") do |config|
    config.vm.box = ENV['UPDATE']
    config.vm.box_url = ENV['BOX_URL']
    config.vm.synced_folder "./", "/vagrant", disabled: true
    
    vms = [
      { :name => "testvm1", :hostname => "testvm1.stress.rbt", :args => "testvm1", :cpus => "4", :memory => "4096", :ip => "10.177.103.151" },
      { :name => "testvm2", :hostname => "testvm2.stress.rbt", :args => "testvm2", :cpus => "4", :memory => "4096", :ip => "10.177.103.152" },
      { :name => "testvm3", :hostname => "testvm3.stress.rbt", :args => "testvm3", :cpus => "4", :memory => "4096", :ip => "10.177.103.153" },
    ]
  
    vms.each do |machine|
      config.vm.define machine[:name] do |node|
        node.vm.hostname = machine[:hostname]
        node.vm.provider :libvirt do |v|
          v.memory = machine[:memory]
          v.cpus = machine[:cpus]
          v.default_prefix = ""
          v.disk_bus = "sata"
        end
        
        node.vm.provision "shell", path:"provision/env_provision.sh", args: [ENV['RC']]
      end
    end
  end

  

