Vagrant.configure("2") do |config|
    config.vm.box = ENV['UPDATE']
    config.vm.box_url = ENV['BOX_URL']
    
    vms = [
      { :name => "testvm1", :hostname => "testvm1.stress.rbt", :args => "testvm1", :cpus => "4", :memory => "4096", :ip => "10.177.103.151" },
      { :name => "testvm2", :hostname => "testvm2.stress.rbt", :args => "testvm2", :cpus => "4", :memory => "4096", :ip => "10.177.103.152" },
      { :name => "testvm3", :hostname => "testvm3.stress.rbt", :args => "testvm3", :cpus => "4", :memory => "4096", :ip => "10.177.103.153" },
    ]
  
    vms.each do |vm|
      if ENV['VM_NAME'] == vm[:name] or ENV['VM_NAME'].nil?
        config.vm.define vm[:name] do |machine|
          machine.vm.hostname = vm[:hostname]
          #machine.vm.network "public_network", ip: vm[:ip]
          machine.vm.provider "libvirt" do |lv|
            lv.check_guest_additions = false
            lv.name = vm[:name]
            lv.memory = vm[:memory]
            lv.cpus = vm[:cpus]
            lv.customize ["modifyvm", :id, "--usb", "off"]
            lv.customize ["modifyvm", :id, "--usbehci", "off"]
   
          end
          #machine.vm.provision "shell", path:"bl_sources.sh"
          #machine.vm.provision "shell", path:"provision/env_provision.sh", args: [vm[:args], ENV['KERNEL'], ENV['RC']]
        end
      end
    end
  end