urls:
  - name: "Allta auth api"
    url: "http://allta.devos.astralinux.ru/api/auth/api/auth/v1/openapi.json"
  - name: "Allta config api"
    url: "http://allta.devos.astralinux.ru/api/config/api/config/v1/openapi.json"    
  - name: "Allta server api"
    url: "http://allta.devos.astralinux.ru/api/server/api/server/v1/openapi.json"
  # - name: "Allta ACS"
  #   url: "http://10.177.103.10:9999/openapi.json"

