apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: dbos
spec:
  selector:
    app: logging-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
