- name: Auditd
  hosts: "{{ HOST }}"
  become: yes
  
  vars:
    KERNEL_VERSION: "5.15"
    SCRIPT_DIR: /home/u/git/stress_test/auditd_benchmark/
    CONFLUENCE_PARENT_PAGE: test
    security_mode: "2"

  tasks:

  - include: ../../tasks/check_kernel_version.yml

  - include: ../../tasks/astra-modeswitch-get.yml

  - include: ../../tasks/astra-modeswitch-set.yml

  - name: Git checkout auditd
    shell:
      cmd: "cd /home/u/git/stress_test && git checkout auditd"

  - name: Copy config localhost to "{{ HOST }}" auditd
    copy:
      src: aub_conf.py
      dest: "{{ SCRIPT_DIR }}"
      owner: u
      group: u
      mode: '0644'
  
  - name: Prepare settings auditd
    shell:
      cmd: "bash aub_prep.sh"
    args:
      chdir: "{{ SCRIPT_DIR }}"

  - name: Download script upload report to ftp
    get_url:
      url: ftp://10.177.5.111/upload/ivelikanov/ftp_upload_report.py 
      dest: "{{ SCRIPT_DIR }}"    

  - name: Include run and publish scripts auditd
    include_tasks: tasks/run_and_publish.yml
    loop:
      - psaud
      - fileaud
      - useraud

  - name: Upload report to 111 auditd
    shell:
      cmd: python3 ftp_upload_report.py -rp "{{ SCRIPT_DIR }}"
    args:
      chdir: "{{ SCRIPT_DIR }}"    

  - name: Git reset auditd
    shell:
      cmd: git reset --hard
    args:
      chdir: "{{ SCRIPT_DIR }}"