# Create pgpool service and allow to retrieve keytab

- name: Kinit admin
  shell: echo {{ domain.admin_password  }} | kinit {{ domain.admin }}

- block:
    - name: Remove pgpool virtual service
      ipa_service:
        force: yes
        name: postgres/{{ virtual_domain_name }}.{{ astra_domain }}
        ipa_host: '{{ hostvars.domain.domain_name }}.{{ astra_domain }}'
        ipa_pass: '{{ domain.admin_password }}'
        state: absent

    - name: Create pgpool virtual service
      command: >-
        ipa service-add postgres/{{ virtual_domain_name }}.{{ astra_domain }} --skip-host-check --force

    - name: Allow to retrieve keytab for admins
      command: >-
        ipa service-allow-retrieve-keytab --groups=admins postgres/{{ virtual_domain_name }}.{{ astra_domain }}
      register: res
      failed_when: res.rc != 0 and 'already a member' not in res.stdout
  when: inventory_hostname == groups.load_balancers_db.0

- name: Remove keytab
  file:
    path: /etc/pgpool2/krb5.keytab
    state: absent

- block:
    - name: Create keytab
      command: >-
        ipa-getkeytab -s {{ hostvars.domain.domain_name }}.{{ astra_domain }} -k /etc/pgpool2/krb5.keytab
                      -p postgres/{{ virtual_domain_name }}.{{ astra_domain }}

    - name: Set signal that keytab for virtual pgpool service was created
      vars:
        signal: pgpool_keytab
      import_tasks: '{{ playbook_dir }}/tasks/set_file_signal.yml'
  when: inventory_hostname == groups.load_balancers_db.0

- block:
    - name: Wait until keytab for virtual pgpool service is created
      vars:
        signal: pgpool_keytab
      import_tasks: '{{ playbook_dir }}/tasks/wait_for_file_signal.yml'

    - name: Retrieve keytab
      command: >-
        ipa-getkeytab -s {{ hostvars.domain.domain_name }}.{{ astra_domain }} -k /etc/pgpool2/krb5.keytab
                      -p postgres/{{ virtual_domain_name }}.{{ astra_domain }} -r
  when: inventory_hostname != groups.load_balancers_db.0