- name: Setup db load balancer
  become: true
  block:
    - name: Install necessary components
      import_tasks: install.yml

    - name: Temporarily disable pgpool2 service
      become: true
      service:
        name: pgpool2
        state: stopped
        enabled: no

    - name: Disable postgresql server
      service:
        name: postgresql
        state: stopped
        enabled: no

    - name: Configure pgpool2
      import_tasks: pgpool2.yml

    - name: Wait until domain controller is ready
      vars:
        signal: domain
      import_tasks: '{{ playbook_dir }}/tasks/wait_for_domain.yml'

    - name: Setup freeipa client
      include_role:
        name: domain_client

    - name: Configure keytabs
      import_tasks: kerberos.yml

    - name: Create dns record for virtual IP
      ipa_dnsrecord:
        ipa_host: '{{ hostvars.domain.domain_name }}.{{ astra_domain }}'
        ipa_pass: '{{ domain.admin_password }}'
        zone_name: '{{ astra_domain }}'
        record_name: '{{ virtual_domain_name }}'
        record_type: A
        record_value: '{{ delegate_ip }}'
        record_ttl: 3600
      register: res
      until: res is not failed
      failed_when: res.msg is defined and 'no modifications to be performed' not in res.msg
      when: inventory_hostname == groups.load_balancers_db.0

    # - name: Wait until standby database replicas are restarted
    #   vars:
    #     signal: db_standby_replicas_restart
    #   import_tasks: '{{ playbook_dir }}/tasks/wait_for_file_signal.yml'
    #   when: server.pg.replication.enabled and server.pg.load_balancing.wait_for_replicas

    - name: Wait for a database replicas are restarted of time
      command: sleep 180
      when: server.pg.replication.enabled and server.pg.load_balancing.wait_for_replicas
      run_once: true

    - name: Reboot machines and restart services
      import_tasks: reboot.yml
