- name: Temporarily disable pgpool2 service
  become: yes
  service:
    name: pgpool2
    state: stopped
    enabled: no

- name: Reboot
  become: yes
  reboot:
    post_reboot_delay: 5

- name: Set signal that host has been rebooted
  vars:
    signal: '{{ inventory_hostname }}_rebooted'
  import_tasks: '{{ playbook_dir }}/tasks/set_file_signal.yml'

# Sync service starting
- name: Wait for other pgpool2 nodes
  vars:
    signal: '{{ item }}_rebooted'
  include_tasks: '{{ playbook_dir }}/tasks/wait_for_file_signal.yml'
  loop: '{{ groups.load_balancers_db | difference([inventory_hostname]) }}'

- name: Enable pgpool2 service
  become: yes
  service:
    name: pgpool2
    state: started
    enabled: yes

# You need to check that there are only one host with delegate_ip.
# If not, something went wrong - the easiest way to handle that is to reboot
# all load balancers at once (using tasks/reboot/lb-db.yml).