"""refactor

Revision ID: a39283418d30
Revises: 725aca8f21bf
Create Date: 2025-07-03 16:27:55.843602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39283418d30'
down_revision: Union[str, Sequence[str], None] = '725aca8f21bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_machines', 'disk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machines', sa.Column('disk', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
