"""refactor models

Revision ID: d92f9eae32ce
Revises: ca02fc0dc997
Create Date: 2025-08-13 11:36:11.873998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92f9eae32ce'
down_revision: Union[str, Sequence[str], None] = 'ca02fc0dc997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm', 'os')
    op.drop_column('vm', 'occupied_by')
    op.drop_column('vm', 'kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('kernel', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('vm', sa.Column('occupied_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vm', sa.Column('os', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
