max_connections = 2000
default_statistics_target = 100
shared_buffers = 512MB
work_mem = 32MB
maintenance_work_mem = 128MB
effective_cache_size = 2GB
random_page_cost = 1.0
checkpoint_timeout = 3min
wal_buffers = 32MB
wal_level = logical
autovacuum = on
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
idle_in_transaction_session_timeout = 60000
listen_addresses = '0.0.0.0'
log_min_duration_statement = 500
password_encryption = md5

