all:
  vars:
    astra_network_ip: 192.168.60
    astra_domain: astra.domain
    0_recreate_vm: no
    0_configure_static_ip: no
  children:

    servers:
      vars:
        1_recreate_vm: no
        1_configure_static_ip: no

      hosts:
        domain:
          ansible_host: 192.168.60.100
          vm_name: Astra Domain
          domain_name: freeipa
          recreate_vm: no
          configure_static_ip: no
          # do not remove these two variables below
          2_recreate_vm: no
          2_configure_static_ip: no

      children:
        web_servers:
          vars:
            2_recreate_vm: no
            2_configure_static_ip: no
          hosts:
            web:
              ansible_host: 192.168.60.101
              vm_name: Astra Web
              domain_name: web
              recreate_vm: no
              configure_static_ip: no

        databases:
          vars:
            2_recreate_vm: no
            2_configure_static_ip: no
          hosts:
            database:
              ansible_host: 192.168.60.102
              vm_name: Astra Database
              domain_name: database
              recreate_vm: no
              configure_static_ip: no

    clients:
      vars:
        1_recreate_vm: no
        1_configure_static_ip: no

      hosts:
        client:
          ansible_host: 192.168.60.103
          vm_name: Astra Client
          domain_name: client
          recreate_vm: no
          configure_static_ip: no

        devops:
          ansible_host: 192.168.60.104
          vm_name: Astra DevOps
          domain_name: devops
          recreate_vm: no
          configure_static_ip: no