[runtime settings]
host = http://nginx
headless = true
only-summary = true
csv = ./results/docker_web_1.7.5.9_5.10.190-1-generic/nginx_docker/results
html = ./results/docker_web_1.7.5.9_5.10.190-1-generic/nginx_docker/results.html

