[runtime settings]
host = http://127.0.0.1
headless = true
only-summary = true
csv = ./results/docker_web_1.8.1.13_6.6.28-1-generic/nginx_server/results
html = ./results/docker_web_1.8.1.13_6.6.28-1-generic/nginx_server/results.html

