[runtime settings]
host = http://172.24.0.2
headless = true
only-summary = true
stop-timeout = 0
csv = ./results/docker_web_1.8.1.12_6.6.28-1-generic/locust_proc/results
html = ./results/docker_web_1.8.1.12_6.6.28-1-generic/locust_proc/results.html

