version: '3.8'
services:
  allta-user-db:
    build:
      context: ./allta_user_db
      dockerfile: Dockerfile.allta_user_db
    image: allta-db:latest
    container_name: allta_user_db
    restart: always
    env_file:
      - ./env/.env.allta_user_db
    volumes:
      - allta_user_db_data:/var/lib/postgresql/data 
    ports:
      - "5433:5432"          
    networks:
      - allta_network

  allta-vm-db:
    build:
      context: ./allta_vm_db
      dockerfile: Dockerfile.allta_vm_db
    image: allta-vm-db:latest
    container_name: allta_vm_db
    restart: always
    env_file:
      - ./env/.env.allta_vm_db
    volumes:
      - allta_vm_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"    
    networks:
      - allta_network


networks:
  allta_network:
    driver: bridge
    
volumes:
    # Внутренние тома
  allta_user_db_data:
    driver: local
    driver_opts:
      type: none
      device: /var/allta_services/volumes/allta_user_db_data
      o: bind
  allta_vm_db_data:
    driver: local
    driver_opts:
      type: none
      device: /var/allta_services/volumes/allta_vm_db_data
      o: bind     