#Project Path
PROJECT_PATH=/home/u/folder_git_for_infocollector/stress_test/allta_infocollector


#Dashboard directory
DB_PATH=/home/u/folder_git_for_infocollector/stress_test/allta_infocollector/src/handler


#Prometheus database directory
#Needed 30GB+ free space available
PM_DB_PATH=/home/partimag/prometheus-data


#Servers where node exporter will be located
SERVERS='10.177.103.201:9100', '10.177.103.202:9100', '10.177.103.203:9100', '10.177.103.204:9100', '10.177.103.205:9100', '10.177.103.101:9100', '10.177.103.102:9100', '10.177.103.103:9100', '10.177.103.104:9100', '10.177.103.206:9100', '10.177.103.207:9100', '10.177.103.208:9100', '10.177.103.209:9100', '10.177.103.10:9100', '10.177.103.11:9100'


#node exporter servers admin user creds
STD_USER=u
STD_PASSWD=1


#Server where allta_infocollector.service will be located
SERVER_IP=10.177.103.10

###!!!
#!!! Before first start run script in this dir:
# python3 config_handler.py && bash install.sh
