#General service name
SERVICE_NAME=allta_infocollector.service

#Project Path
S_PATH=/home/u/folder_git_for_infocollector/stress_test/allta_infocollector
DB_PATH=/home/u/folder_git_for_infocollector/stress_test/allta_infocollector/src/handler

#Servers collection
SERVERS=['10.177.103.201:9100', '10.177.103.202:9100', '10.177.103.203:9100', '10.177.103.204:9100', '10.177.103.205:9100']


G_PATH=/home/u/folder_git_for_infocollector/stress_test/allta_infocollector/src/handler


#node exporter nodes user creds
std_user=u
std_password=1

project_path=/home/u/folder_git_for_infocollector/stress_test/allta_infocollector

server_ip=10.177.103.10


