#####################################
# Created by dtimonin@astralinux.ru #
#####################################

# Results Path
RESULTS_NAME=results.txt

# Postgresql version
PSQL_VERSION=15

# Postgresql conf
CLUSTER_PORT=6000
CONNECTIONS_COUNT=300
TRANSACTION_TIME=30
# Основные параметры можно подобрать индивидуально под свою машину:
# https://pgtune.fariton.ru/
SHARED_BUFFERS=32256MB
EFFECTIVE_CACHE_SIZE=96768MB
WORK_MEM=41287kB
MAX_WORKER_PROCESSES=32
MAX_PARALLEL_WORKERS=32