class ExitCodes:
    OK = 0
    PRECHECK_MISSING_DEPS = 10
    PRECHECK_SERVICE = 11
    PRECHECK_KVM = 12
    PRECHECK_NAME_CONFLICT = 13
    PRECHECK_NO_SPACE = 14
    ACTION_FAILED = 20
    VERIFY_FAILED = 30
    UNEXPECTED = 50