apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://auth_user:change_me@postgres-rw.auth-service.svc.cluster.local:5432/auth_db
  SECRET_KEY: change-me
