- name: Set vm name
  set_fact:
    vm_name: "{{ hostvars[host].vm_name | regex_escape('posix_basic') }}"

- name: Stop vm
  command: |
    vboxmanage controlvm "{{ vm_name }}" poweroff
  register: result
  failed_when: result.rc != 0 and "not currently running" not in result.stderr
  when: vbox_vm_exist[host]

- block:
    - name: Remove vm
      command: |
         vboxmanage unregistervm "{{ vm_name }}" --delete

    - name: Clear variable
      set_fact:
        vbox_vm_exist: "{{ vbox_vm_exist | combine({host: false}) }}"
  when: recreate_vm[host] and vbox_vm_exist[host]

- block:
    - name: Set ova file path for servers
      set_fact:
        ova_path: '{{ vm.images_base_paths.vanilla }}'
      when: host in groups.servers

    - name: Set ova file path for clients
      set_fact:
        ova_path: '{{ vm.images_base_paths.vanilla_gui }}'
      when: host in groups.clients

    - name: Create folder for Vbox VMs
      file:
        path: '{{ vm.vbox.folder }}'
        state: directory

    - name: Import ova
      shell:
        cmd: vboxmanage import "{{ ova_path }}" --vsys 0 --vmname "{{ vm_name }}" --basefolder "{{ vm.vbox.folder }}"
  when: recreate_vm[host] or not vbox_vm_exist[host]

- name: Configure vm
  shell: |
    sleep 1
    vboxmanage modifyvm "{{ vm_name }}" \
    --nic1 hostonly --nictype1 virtio --hostonlyadapter1 {{ vbox_hostonly_ifname }} --nic2 nat --nictype2 virtio \
    {% if host in groups.servers %}
      {% if host == 'domain' %}
        --cpus 1 --memory 2048
      {% else %}
        --cpus 1 --memory 1024
      {% endif %}
    {% else %}
      --cpus 2 --memory 2048
    {% endif %}

- name: Start vm
  command: |
    vboxmanage startvm "{{ vm_name }}" --type headless