- block:
    - name: Get MAC address of host-only interface
      shell: |
        vboxmanage showvminfo "{{ hostvars[host].vm_name | regex_escape('posix_basic') }}" | \
        awk '/.*MAC:.*Host-only.*/ {print $4}' | tr -d ','
      register: hostonly_mac

    - name: Get DHCP ip address lease
      shell: |
        vboxmanage dhcpserver findlease \
        --interface {{ vbox_hostonly_ifname }} --mac-address={{ hostonly_mac.stdout }} | awk 'NR==1{print $3}'
      register: lease
      until: "'error' not in lease.stderr"
      retries: 10
      delay: 8

    - name: Remove host from known for SSH
      command: |
        ssh-keygen -f "~/.ssh/known_hosts" -R {{ lease.stdout }}
      register: res
      changed_when: false
      failed_when: 'res.rc != 0 and "exists" not in res.stderr'

    - name: Set temporal IP variable
      set_fact:
        vbox_temp_ip: "{{ dict(vbox_temp_ip | default({})) | combine({host: lease.stdout}) }}"

    - debug:
        var: lease.stdout

    - name: Temporarily set different ansible_host
      add_host:
        hostname: '{{ host }}'
        ansible_host: '{{ lease.stdout }}'
        true_ansible_host: '{{ hostvars[host].ansible_host }}'

    - name: Set flag to configure static network
      set_fact:
        vbox_configure_static_net: "{{ dict(vbox_configure_static_net | default({})) | combine({host: True}) }}"

  when: not vbox_vm_exist[host] or vbox_configure_static_ip[host]