Vagrant.configure("2") do |config|
    config.vm.box = ENV['UPDATE']
  
    config.vm.define "db1" do |db1|
      db1.vm.hostname = "db1.balance.rbt"
      db1.vm.provider "virtualbox" do |vb|
        vb.check_guest_additions = false
        vb.name = "db1"
        vb.memory = "4096"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
      db1.vm.provision "shell", path:"provision/env_provision.sh", args: ["db1"]
    end
        
    config.vm.define "db2" do |db2|
      db2.vm.hostname = "db2.balance.rbt"
      db2.vm.provider "virtualbox" do |vb|
        vb.check_guest_additions = false
        vb.name = "db2"
        vb.memory = "4096"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
      db2.vm.provision "shell", path:"provision/env_provision.sh", args: ["db2"]
    end

    config.vm.define "db3" do |db3|
      db3.vm.hostname = "db3.balance.rbt"
      db3.vm.provider "virtualbox" do |vb|
        vb.check_guest_additions = false
        vb.name = "db3"
        vb.memory = "4096"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
      end
      db3.vm.provision "shell", path:"provision/env_provision.sh", args: ["db3"]
    end
end

