Vagrant.configure("2") do |config|
  config.vm.box = ENV['UPDATE']
  
  vms = [
    { :name => "database1", :hostname => "database1.balance.rbt", :args => "database1", :cpus => "2" },
    { :name => "database2", :hostname => "database2.balance.rbt", :args => "database2", :cpus => "2" },
    { :name => "database3", :hostname => "database3.balance.rbt", :args => "database3", :cpus => "2" },
    { :name => "lbdb1", :hostname => "lbdb1.balance.rbt", :args => "lbdb1", :cpus => "2" },
    { :name => "lbdb2", :hostname => "lbdb2.balance.rbt", :args => "lbdb2", :cpus => "2" },
    { :name => "lbdb3", :hostname => "lbdb3.balance.rbt", :args => "lbdb3", :cpus => "2" },
    { :name => "pgpool", :hostname => "pgpool.balance.rbt", :args => "pgpool", :cpus => "4" },
    { :name => "dc_freeipa", :hostname => "dc_freeipa.balance.rbt", :args => "dc_freeipa", :cpus => "4" }
  ]

  vms.each do |vm|
    config.vm.define vm[:name] do |machine|
      machine.vm.hostname = vm[:hostname]
      machine.vm.provider "virtualbox" do |vb|
        vb.check_guest_additions = false
        vb.name = vm[:name]
        vb.memory = "4096"
        vb.cpus = vm[:cpus]
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
        vb.customize ["modifyvm", :id, "--nic1", "nat"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet0"]
      end
      machine.vm.provision "shell", path:"provision/env_provision.sh", args: [vm[:args]]
    end
  end
end

