Vagrant.configure("2") do |config|
  config.vm.box = ENV['UPDATE']
  
  vms = [
    { :name => "db1", :hostname => "db1.balance.rbt", :script_args => "db1" },
    { :name => "db2", :hostname => "db2.balance.rbt", :script_args => "db2" },
    { :name => "db3", :hostname => "db3.balance.rbt", :script_args => "db3" }
  ]

  vms.each do |vm|
    config.vm.define vm[:name] do |machine|
      machine.vm.hostname = vm[:hostname]
      machine.vm.provider "virtualbox" do |vb|
        vb.check_guest_additions = false
        vb.name = vm[:name]
        vb.memory = "4096"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
        vb.customize ["modifyvm", :id, "--nic1", "nat"]
        vb.customize ["modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet0"]
      end
      machine.vm.provision "shell", path:"provision/env_provision.sh", args: [vm[:script_args]]
    end
  end
end

