[runtime settings]
host = http://127.0.0.1
users = 3500

spawn-rate = 20
run-time = 5m
headless = true
only-summary = true
csv = /home/u/git/stress_test/docker/site/Kuznechik/for_host/results/results
html = /home/u/git/stress_test/docker/site/Kuznechik/for_host/results/results.html

