[runtime settings]
host = http://10.177.103.205
users = 600

spawn-rate = 10
run-time = 1m
headless = true
only-summary = true
csv = /app/Kuznechik/for_host/results/results
html = /app/Kuznechik/for_host/results/results.html
