[runtime settings]
host = http://127.0.0.1
users = 2500

spawn-rate = 15
run-time = 5m
headless = true
only-summary = true
csv = /app/Kuznechik/for_host/results/results
html = /app/Kuznechik/for_host/results/results.html

