- name: Check internet connection
  command: |
    ping -c 3 10.0.2.2
  register: ping
  changed_when: ping.rc != 0
  failed_when: false

- name: Configure network interfaces directly (most likely there is no network-manager)
  become: yes
  block:
    - name: Create interfaces.d
      file:
        path: /etc/network/interfaces.d/
        state: directory

    - name: Create internet network interface config
      blockinfile:
        path: /etc/network/interfaces.d/eth1.cfg
        create: yes
        block: |
          # The internet network interface
          allow-hotplug eth1
          iface eth1 inet dhcp

    - name: Restart internet network interface
      shell: |
        ifdown eth1 ; sleep 1 ; ifup eth1
      register: result
      failed_when: 'result.rc != 0 and "ifdown: interface eth1 not configured" not in result.stderr'
  when: ping.rc != 0
