- name: Wait for SSH
  wait_for_connection:
    timeout: 900
    sleep: 2
  when: contrprimer.env != 'yandex'

- become: yes
  block:
    - name: Check MAC and MIC control
      shell: |
        astra-mac-control status
        astra-mic-control status
      changed_when: false
      failed_when: false
      register: mac_mic_status

    - name: Enable Smolensk mode and MAC, MIC control
      shell: |
        astra-modeswitch set 2
        astra-mac-control enable
        astra-mic-control enable
      when: mac_mic_status.stdout == 'НЕАКТИВНО\nНЕАКТИВНО'

    - name: Reboot
      reboot:
        post_reboot_delay: 5
      when: mac_mic_status.stdout == 'НЕАКТИВНО\nНЕАКТИВНО'
  when: not debian_linux

- name: Configure network
  import_tasks: network.yml

- name: Perform system upgrade
  import_tasks: system_upgrade.yml

- become: yes
  block:
    - name: Install necessary components
      apt:
        name:
          - mc
          - htop
          - rsync
          - aptitude
      register: result
      until: result is not failed

    # TODO: remove "GUI" variable from inventory
    - name: Check whether machine has GUI
      stat:
        path: /etc/X11/fly-dm
      register: fly_dm

    - block:
        - name: Set screen resolution
          copy:
            src: xorg.conf
            dest: /etc/X11/xorg.conf

        - name: Set DPI
          copy:
            content: 96
            dest: /etc/X11/fly-dm/dpi
      when: 'inventory_hostname in groups.clients and fly_dm.stat.exists'