- include: ../rollback_snapshot.yml 

- name: FILEAUD
  hosts: "{{ HOST }}"
  become: yes
  
  vars:
    KERNEL_VERSION: "{{ KERNEL_VERS }}"
    SCRIPT_DIR: /home/u/git/stress_test/auditd_benchmark/
    CONFLUENCE_PARENT_PAGE: test
    security_mode: "{{ SECURITY_MODE }}"

  tasks:

  - include: ../tasks/check_kernel_version.yml

  - include: ../tasks/astra-modeswitch-get.yml

  - include: ../tasks/astra-modeswitch-set.yml

  - name: Git checkout auditd
    shell:
      cmd: "cd /home/u/git/stress_test && git checkout auditd"

  - name: Copy config localhost to "{{ HOST }}" fileaud
    copy:
      src: aub_conf.py
      dest: "{{ SCRIPT_DIR }}"
      owner: u
      group: u
      mode: '0644'

  - name: Prepare settings fileaud
    shell:
      cmd: "bash aub_prep.sh"
    args:
      chdir: "{{ SCRIPT_DIR }}"
  
  - name: Download script upload report to ftp
    get_url:
      url: ftp://10.177.5.111/upload/ivelikanov/ftp_upload_report.py 
      dest: "{{ SCRIPT_DIR }}"

  - name: Run stress test fileaud
    shell:
      cmd: "venv/bin/python aub_run.py --testlist fileaud --mode default"
    args:
      chdir: "{{ SCRIPT_DIR }}"

  - name: Publish in life fileaud
    shell:
      cmd: venv/bin/python aub_publish.py -u "{{ USER_LIFE }}" -t "{{ TOKEN_LIFE }}" -cs "{{ CONFLUENCE_SPACE }}" -cpp "{{ CONFLUENCE_PARENT_PAGE }}" -cnp aub_fileaud_test_{{ astra_version.stdout }}_{{ kernel_version.stdout }} -rp "{{ SCRIPT_DIR }}report" -pack auditd -ts fileaud
    args:
      chdir: "{{ SCRIPT_DIR }}"

  - name: Upload report to 111 fileaud
    shell:
      cmd: python3 ftp_upload_report.py -rp "{{ SCRIPT_DIR }}"
    args:
      chdir: "{{ SCRIPT_DIR }}"