from __future__ import annotations

import os
import re
import shlex
import tempfile
import json
from glob import glob
from pathlib import Path
from shutil import which, rmtree

from allta import SystemCommands
from allta_cli.utils.config import PYTHON_PATH, PYTHON_GET_COMMAND

_PRIVATE_INDEX = "http://10.177.103.10:3141/root/release"
_PRIVATE_HOST = "10.177.103.10"

SEP = "─" * 60


def _sudo() -> str:
    try:
        if os.geteuid() == 0:
            return ""
    except AttributeError:
        return ""
    return "sudo " if which("sudo") else ""


def _run(cmd: str, fail: str) -> int:
    print(f"$ {cmd}")
    rc = SystemCommands.cmd_with_returncode(command=cmd)
    if rc != 0:
        print(f"✗ {fail} (код {rc})")
    return rc


def _find_archive(d: Path) -> Path | None:
    files = sorted(glob(str(d / "Python-*.tar.xz")))
    return Path(files[-1]) if files else None


def _find_installed_python() -> Path | None:
    """Предпочтительно берём python3.X из /usr/local/bin, затем из PATH."""
    for p in sorted(Path("/usr/local/bin").glob("python3.*")):
        if p.is_file() and os.access(p, os.X_OK):
            return p
    p = which("python3")
    return Path(p) if p else None


def _spawn_shell_with_venv(venv_dir: Path) -> None:
    """
    Запускает новый интерактивный bash с уже активированным venv.
    Текущий процесс ЗАМЕНЯЕТСЯ на shell (os.execve).
    """
    bash = which("bash") or "/bin/bash"
    rcfile = Path(tempfile.mkstemp(prefix="allta-venv-", suffix=".rc")[1])
    rc_content = f"""# auto-generated by allta
source {venv_dir}/bin/activate
PS1="(venv) $PS1"
echo "✓ Venv активирован: {venv_dir}"
"""
    rcfile.write_text(rc_content, encoding="utf-8")
    os.execve(bash, [bash, "--rcfile", str(rcfile), "-i"], os.environ)


def install_python(activate_shell: bool = False) -> int:
    """
    1) Устанавливает build-зависимости (apt)
    2) Скачивает архива(ы) Python в PYTHON_PATH
    3) Собирает и устанавливает (make altinstall) — системно (/usr/local), если есть sudo
    4) Создаёт venv по умолчанию: ~/python/Python-<VER>/venv
    5) Устанавливает allta в этот venv
    6) ЧИСТИТ: удаляет архивы и исходники, оставляя только venv
    7) (опционально) заменяет процесс на bash с активированным venv
    """
    print(SEP)
    print("PYTHON INSTALL (start)")
    print(SEP)

    sudo = _sudo()
    root = PYTHON_PATH.expanduser()
    root.mkdir(parents=True, exist_ok=True)

    print("→ Установка зависимостей сборки (apt)…")
    env = "DEBIAN_FRONTEND=noninteractive"
    deps = (
        "build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev "
        "libffi-dev libncursesw5-dev tk-dev libgdbm-dev libnss3-dev liblzma-dev uuid-dev "
        "xz-utils curl wget ca-certificates"
    )
    rc = _run(f"{sudo}{env} apt-get -y update", "apt-get update")
    if rc != 0:
        return rc
    rc = _run(f"{sudo}{env} apt-get -y install {deps}", "apt-get install")
    if rc != 0:
        return rc

    print("↓ Скачивание архива Python (wget)…")
    rc = _run(PYTHON_GET_COMMAND, "скачивание архива Python")
    if rc != 0:
        return rc

    archive = _find_archive(root) or _find_archive(Path("."))
    if not archive:
        print("✗ Не найден архив Python-*.tar.xz после скачивания.")
        return 1
    print(f"✓ Найден архив: {archive}")

    m = re.search(r"Python-(\d+\.\d+\.\d+)", archive.name)
    if not m:
        print("✗ Не удалось распознать версию из имени архива.")
        return 1
    version = m.group(1)
    major_minor = ".".join(version.split(".")[:2])

    print("↪ Распаковка…")
    rc = _run(
        f"tar -xf {shlex.quote(str(archive))} -C {shlex.quote(str(root))}",
        "распаковка архива",
    )
    if rc != 0:
        return rc

    src_dir = root / f"Python-{version}"
    if not src_dir.is_dir():
        print(f"✗ Каталог исходников не найден: {src_dir}")
        return 1

    print("⚙ ./configure …")
    rc = _run(
        f"bash -lc 'cd {shlex.quote(str(src_dir))} && ./configure --enable-optimizations'",
        "./configure",
    )
    if rc != 0:
        return rc

    jobs = str(os.cpu_count() or 1)
    print(f"🔨 make -j{jobs} …")
    rc = _run(
        f"bash -lc 'cd {shlex.quote(str(src_dir))} && make -j{jobs}'", "сборка (make)"
    )
    if rc != 0:
        return rc

    print("📦 make altinstall …")
    rc = _run(
        f"bash -lc 'cd {shlex.quote(str(src_dir))} && {sudo}make altinstall'",
        "установка (make altinstall)",
    )
    if rc != 0:
        return rc


    py_bin = Path(f"/usr/local/bin/python{major_minor}")
    if not py_bin.exists():
        py_bin = _find_installed_python()
    if not py_bin or not py_bin.exists():
        print(
            f"✗ Не найден установленный python{major_minor}. Смотри вывод altinstall."
        )
        return 1
    print(f"✓ Python обнаружен: {py_bin}")

    venv_dir = src_dir / "venv"
    print(f"⚙ Создание venv: {venv_dir}")
    rc = _run(
        f"{shlex.quote(str(py_bin))} -m venv {shlex.quote(str(venv_dir))}",
        "создание venv",
    )
    if rc != 0:
        return rc

    pip_bin = venv_dir / "bin" / "pip"
    if not pip_bin.exists():
        print("✗ pip в venv не найден.")
        return 1

    print("↓ Установка пакета allta в venv (приватный индекс)…")
    rc = _run(
        f"{shlex.quote(str(pip_bin))} install -i {_PRIVATE_INDEX} --trusted-host {_PRIVATE_HOST} allta",
        "установка пакета allta",
    )
    if rc != 0:
        return rc

    # 6) CLEANUP: удаляем архивы и исходники, но оставляем venv
    print("🧹 Очистка: удаляем архив и исходники…")
    try:
        # архив
        try:
            archive.unlink()
        except Exception:
            pass
        # удаляем всё в src_dir, КРОМЕ venv
        for child in src_dir.iterdir():
            if child.name == "venv":
                continue
            if child.is_dir():
                rmtree(child, ignore_errors=True)
            else:
                try:
                    child.unlink()
                except Exception:
                    pass
        print("✓ Очистка завершена.")
    except Exception as e:
        print(f"⚠ Ошибка очистки: {e} (пропускаем)")

    print("✓ Готово.")
    print(SEP)
    print("PYTHON INSTALL (end)")
    print(SEP)

    # 7) По запросу — сразу открыть интерактивный shell с активированным venv
    if activate_shell:
        _spawn_shell_with_venv(venv_dir)

    return 0


def create_venv(path: str | None = None, enter_shell: bool = False) -> int:
    """
    Создаёт venv:
      - если path НЕ указан: venv в текущей директории ./venv
      - если path указан: КАТАЛОГ ДОЛЖЕН СУЩЕСТВОВАТЬ, иначе — ошибка
    Использует системный /usr/local/bin/python3.X (если есть), иначе python3 из PATH.
    При успехе по умолчанию запускает интерактивный bash с активированным venv.
    """
    if path:
        target = Path(path).expanduser()
        if not target.exists():
            print(f"✗ Указанный путь не существует: {target}")
            return 1
    else:
        target = Path.cwd() / "venv"

    if target.exists() and target.is_dir() and any(target.iterdir()):
        print(f"✗ Целевой каталог уже существует и не пуст: {target}")
        return 1
    target.mkdir(parents=True, exist_ok=True)

    py_bin = _find_installed_python()
    if not py_bin:
        print("✗ Не найден подходящий python3. Сначала выполните: allta python")
        return 1

    print(f"→ Использую интерпретатор: {py_bin}")
    rc = _run(
        f"{shlex.quote(str(py_bin))} -m venv {shlex.quote(str(target))}",
        "создание venv",
    )
    if rc != 0:
        return rc

    print("✓ Venv создан.")
    if enter_shell:
        _spawn_shell_with_venv(target)

    return 0
