FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ENV LOCUST_FILE=locustfile.py

WORKDIR /app/Kuznechik

CMD ["locust", "-f", "locustfile.py", "--config", ".locust.conf", "--headless"]