FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    apache2 \
    apache2-utils \
    libapache2-mod-wsgi-py3 \
    && apt-get clean

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /app

RUN mkdir -p /usr/local/apache2/htdocs
RUN mkdir -p /usr/local/apache2/logs

RUN rm -f /etc/apache2/mods-enabled/mpm_event.conf /etc/apache2/mods-enabled/mpm_prefork.conf
RUN a2dismod mpm_event mpm_prefork || true
RUN a2enmod mpm_worker

COPY apache-config/mpm_worker.conf /etc/apache2/mods-available/mpm_worker.conf
RUN ln -sf /etc/apache2/mods-available/mpm_worker.conf /etc/apache2/mods-enabled/mpm_worker.conf

COPY ./apache-config/apache2.conf /etc/apache2/apache2.conf
COPY ./apache-config/web-app.conf /etc/apache2/sites-available/web-app.conf

RUN a2ensite web-app.conf
RUN a2enmod wsgi

RUN chown -R www-data:www-data /app/web_app
RUN chmod -R 755 /app/web_app


EXPOSE 80
