FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    apache2 \
    apache2-utils \
    libapache2-mod-wsgi-py3 \
    && apt-get clean

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /app

RUN mkdir -p /usr/local/apache2/htdocs
RUN mkdir -p /usr/local/apache2/logs

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

COPY ./apache-config/web-app.conf /etc/apache2/sites-available/web-app.conf
RUN a2ensite web-app.conf

RUN a2enmod wsgi

RUN chown -R www-data:www-data /app/web_app
RUN chmod -R 755 /app/web_app

RUN chmod +x migrate.sh

EXPOSE 80
