FROM locustio/locust:2.35.0

USER root

RUN printf '%s\n' \
    '[global]' \
    'index-url = http://allta.devos.astralinux.ru:3141/root/release' \
    'trusted-host = allta.devos.astralinux.ru' \
    > /etc/pip.conf \
    && chmod 0644 /etc/pip.conf

# Устанавливаем allta из локального DevPI-сервера
RUN pip install allta
