FROM python:3.11

WORKDIR /app

# Установка зависимостей
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Установка Apache и модуля WSGI
RUN apt-get update && apt-get install -y \
    apache2 \
    apache2-utils \
    libapache2-mod-wsgi-py3 \
    && apt-get clean

# Создание необходимых директорий
RUN mkdir -p /usr/local/apache2/htdocs
RUN mkdir -p /usr/local/apache2/logs

# Настройка ServerName
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Копирование конфигурации Apache
COPY ./apache-config/web-app.conf /etc/apache2/sites-available/web-app.conf
RUN a2ensite web-app.conf

# Включение модулей Apache
RUN a2enmod wsgi

COPY . /app
# Настройка прав доступа
RUN chown -R www-data:www-data /app/web_app
RUN chmod -R 755 /app/web_app

# Копирование исходного кода

# Открытие порта 80
EXPOSE 80

# Запуск Apache
CMD ["apache2ctl", "-D", "FOREGROUND"]