FROM allta.devos.astralinux.ru:21503/python:3.11

# Allta devpi package index
RUN pip config --global set global.index-url http://allta.devos.astralinux.ru:3141/root/release && pip config --global set global.trusted-host allta.devos.astralinux.ru

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip -i https://artifactory.astralinux.ru/artifactory/api/pypi/gca-pypi-remote/simple --trust artifactory.astralinux.ru
RUN pip install -r requirements.txt -i https://artifactory.astralinux.ru/artifactory/api/pypi/gca-pypi-remote/simple --trust artifactory.astralinux.ru


COPY . /app

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "--chdir", "/app/web_app", "wsgi:application"]



