version: '3.1'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      bash -c "PGPASSWORD=${POSTGRES_PASSWORD} 
      psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} 
      -h localhost -c 'DROP SCHEMA public CASCADE; 
      CREATE SCHEMA public;' && exec postgres"
    ports:
      - "54321:5432"
    networks:
      - httpnet

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask
    volumes:
      - ./flask-upload:/app/web_app/static/upload
      - ./apache-config:/etc/apache2/sites-available
      - ./web_app:/app/web_app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=web_app:create_app
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - httpnet
    command: ["apache2ctl", "-D", "FOREGROUND"]

  master:
    image: locustio/locust
    user: root
    volumes:
      - .:/app
    ports:
      - "8089:8089"
    depends_on:
      - flask
    networks:
      - httpnet
    command: >
      -f /app/Kuznechik/for_docker/locustfile.py
      --master
      --config /app/Kuznechik/for_docker/.locust.conf

  worker:
    image: locustio/locust
    user: root
    depends_on:
      - master
    volumes:
      - .:/app
    networks:
      - httpnet
    command: -f /app/Kuznechik/for_docker/locustfile.py --worker --master-host master --config /app/Kuznechik/for_docker/.locust.conf

networks:
  httpnet:
    driver: bridge