version: '3.5'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask.nginx
    container_name: flask
    volumes:
      - ./flask-upload:/app/web_app/static/upload
      - ./web_app:/app/web_app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - FLASK_APP=web_app:create_app

    networks:
      httpnet:
        ipv4_address: 172.24.0.3
        
  nginx:
    image: allta.devos.astralinux.ru:21503/nginx:latest
    container_name: nginx
    volumes:
    - ./web_app/static:/app/web_app/static
    - ./nginx-config:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      httpnet:
        ipv4_address: 172.24.0.2

  master:
    build:
      context: .
      dockerfile: Dockerfile.locust
    user: root
    container_name: master
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8089:8089"
    depends_on:
      - nginx
    networks:
      - httpnet
    command: >
      -f /app/Kuznechik/locustfile.py
      --master --master-bind-host 0.0.0.0 --expect-workers 5
      --config /app/Kuznechik/.locust.conf
      --headless

  worker:
    build:
      context: .
      dockerfile: Dockerfile.locust
    user: root
    depends_on:
      - master
    volumes:
      - ./:/app
    networks:
      - httpnet
    command: -f /app/Kuznechik/locustfile.py --worker --master-host master --master-port 5557
    restart: on-failure

networks:
  httpnet:
    name: httpnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24



