FROM allta.devos.astralinux.ru:21503/python:3.11

RUN printf '%s\n' \
    '[global]' \
    'index-url = http://allta.devos.astralinux.ru:3141/root/release' \
    'trusted-host = allta.devos.astralinux.ru' \
    > /etc/pip.conf \
    && chmod 0644 /etc/pip.conf

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


COPY . /app

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "--chdir", "/app/web_app", "wsgi:application"]


