FROM locustio/locust:2.35.0

# Allta devpi package index
RUN pip config --global set global.index-url http://allta.devos.astralinux.ru:3141/root/release && pip config --global set global.trusted-host allta.devos.astralinux.ru

USER root

# Устанавливаем allta из локального DevPI-сервера
RUN pip install -i http://10.177.103.10:3141/root/release --trusted-host 10.177.103.10 allta
