"""Database creation

Revision ID: d2774cbe5d56
Revises: 
Create Date: 2024-02-21 18:07:10.103793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2774cbe5d56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('user_admin', sa.String(), nullable=False),
    sa.Column('pass_admin', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('digit_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('stand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('versions')
    op.drop_table('stands')
    # ### end Alembic commands ###
