- name: List all VMs
  virt:
    command: list_vms
  register: all_vms

- name: Evaluate boolean expression
  set_fact:
    to_remove: '{{ recreate_vm[instance.role] and (instance.vm_name in all_vms.list_vms) }}'

- name: Stop VM
  virt:
    state: destroyed
    name: '{{ instance.vm_name }}'
  when: to_remove

- name: Remove VM from qemu
  virt:
    command: undefine
    name: '{{ instance.vm_name }}'
  when: to_remove

- name: Create VM
  shell:
    virt-install --connect qemu:///system --import --check path_in_use=off --noautoconsole \
    --os-variant debian10 --name {{ instance.vm_name }} \
    --network network=astra-network,mac={{ hostvars[instance.role].mac }} \
    --network default \
    {% if instance.type == 'vanilla' %}
      {% if instance.role == 'domain' %}
          --memory 2048 --vcpus 1 \
      {% else %}
          --memory 1024 --vcpus 1 \
      {% endif %}
    {% else %}
          --memory 2048 --vcpus 2 \
    {% endif %}
    --disk {{ (instance.type == 'vanilla') | ternary(
               vm.images_base_paths.vanilla + instance.role + '.qcow2',
               vm.images_base_paths.vanilla_gui + instance.role + '.qcow2') }},bus=sata
  when: 'recreate_vm[instance.role] or (instance.vm_name not in all_vms["list_vms"])'

- name: Start VM
  virt:
    state: running
    name: '{{ instance.vm_name }}'