version: "3.8"

services:
  web:
    build: .
    container_name: apache-server
    networks:
      mynetwork:
        ipv4_address: 172.21.0.3
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24