Listen 80

ServerName localhost

LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
LoadModule rewrite_module modules/mod_rewrite.so

<VirtualHost *:80>
    DocumentRoot "/usr/local/apache2/htdocs"
    ServerName localhost

    RewriteEngine On

    RewriteCond %{REQUEST_METHOD} ^POST$
    RewriteRule ^/post-example$ /post-example.php [L]

    RewriteCond %{REQUEST_METHOD} ^DELETE$
    RewriteRule ^/delete-example$ /delete-example.php [L]

    RewriteCond %{REQUEST_METHOD} ^HEAD$
    RewriteRule ^/head-example$ /head-example.php [L]
</VirtualHost>