"""add_previous_token_hash_to_sessions

Revision ID: 8c217337ea4a
Revises: 6dd91b9272e2
Create Date: 2026-04-18 18:06:41.488617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c217337ea4a'
down_revision: Union[str, None] = '6dd91b9272e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('previous_token_hash', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_sessions_previous_token_hash'), 'sessions', ['previous_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_previous_token_hash'), table_name='sessions')
    op.drop_column('sessions', 'previous_token_hash')
    # ### end Alembic commands ###
