"""nullable_department_for_account_admin

Revision ID: 8d83e2e0bcb9
Revises: 979c718e933c
Create Date: 2026-04-18 12:46:50.005007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d83e2e0bcb9'
down_revision: Union[str, None] = '979c718e933c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
