[runtime settings]
host = http://flask
users = 3000
spawn-rate = 10
run-time = 15m
headless = true
only-summary = true
csv = /app/Kuznechik/for_docker/results/results
html = /app/Kuznechik/for_docker/results/results.html