[runtime settings]
host = http://nginx
users = 2500
spawn-rate = 15

run-time = 5m
headless = true
only-summary = true
csv = /app/Kuznechik/for_docker/results/results
html = /app/Kuznechik/for_docker/results/results.html
