FROM httpd:latest

RUN apt-get update
RUN apt-get install systemctl apache2 python3 python3-pip python3-dev libapache2-mod-wsgi-py3 -y
RUN apt-get clean
RUN systemctl start apache2

WORKDIR /var/www/

COPY ./web-app .
COPY ./venv_prepare.sh ./web-app/
COPY ./requirements.txt ./web-app/
COPY .flaskenv .

RUN chown -R www-data:www-data /usr/local/apache2/htdocs/
RUN chmod -R 755 /usr/local/apache2/logs

RUN cd ./web-app
RUN chmod 777 venv_prepare.sh
RUN bash venv_prepare.sh

COPY ./web-app/flask_app.conf /etc/apache2/sites-available/000-default.conf
# COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

EXPOSE 80
RUN a2enmod wsgi

CMD ["httpd-foreground"]