version: '3'

services:
  
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile.web-app
    container_name: apache-server
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: bash -c "source /var/www/web-app/.venv/bin/activate && flask db upgrade && httpd-foreground"
    depends_on:
      - db
    networks:
      mynetwork:
        ipv4_address: 172.21.0.5

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg/web-data:/var/lib/postgresql/data
    networks:
      mynetwork:
        ipv4_address: 172.21.0.6

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24