
version: "3.1"
services:

  
  nginx:
    image: nginx
    container_name: nginx
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    networks:
      load-network:
        ipv4_address: 172.21.0.2


networks:
  load-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
