version: '3.1'

services:

  base:
    build:
      context: .
      args:
        BASE_IMAGE: ubuntu:latest
    image: stress_test_image

  stress_1:
    image: stress_test_image
    container_name: stress_1
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_2:
    image: stress_test_image
    container_name: stress_2
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_3:
    image: stress_test_image
    container_name: stress_3
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_4:
    image: stress_test_image
    container_name: stress_4
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_5:
    image: stress_test_image
    container_name: stress_5
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_6:
    image: stress_test_image
    container_name: stress_6
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_7:
    image: stress_test_image
    container_name: stress_7
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_8:
    image: stress_test_image
    container_name: stress_8
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_9:
    image: stress_test_image
    container_name: stress_9
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_10:
    image: stress_test_image
    container_name: stress_10
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_11:
    image: stress_test_image
    container_name: stress_11
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_12:
    image: stress_test_image
    container_name: stress_12
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_13:
    image: stress_test_image
    container_name: stress_13
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_14:
    image: stress_test_image
    container_name: stress_14
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true

  stress_15:
    image: stress_test_image
    container_name: stress_15
    command: ["stress", "--vm", "1", "--vm-bytes", "1024M", "--cpu", "1", "--timeout", "60"]
    stdin_open: true
    tty: true
