FROM redis:7-alpine

# Унифицируем через ENV
ENV REDIS_PORT=6379

EXPOSE 6379

# Запуск через команду из Dockerfile
CMD ["sh", "-lc", "exec redis-server --save 60 1 --loglevel warning --port \"$REDIS_PORT\""]