[libdefaults]
        default_realm = ALD.PRO
# The following krb5.conf variables are only for MIT Kerberos.
        kdc_timesync = 1
        ccache_type = 4
        forwardable = true
        proxiable = true
        rdns = false
# The following libdefaults parameters are only for Heimdal Kerberos.
        fcc-mit-ticketflags = true
        dns_lookup_realm = true
        dns_lookup_kdc = true
        rdns = false
        dns_canonicalize_hostname = false
[realms]
        ALD.PRO = {
                kdc = aldprodc1.ald.pro
                admin_server = aldprodc1.ald.pro
                default_domain = ald.pro
        }
        MSAD.PRO = {
                kdc = dc1.msad.pro
                admin_server = dc1.msad.pro
                default_domain = msad.pro
        }

[domain_realm]
        .ald.pro = ALD.PRO
         ald.pro = ALD.PRO
        .msad.pro = MSAD.PRO
         msad.pro = MSAD.PRO
