#!/usr/bin/env bash
# Generates the sudoers snippet for ONE department's emm-host-control
# account, restricted to exactly the systemd units that department chose
# to expose. Every department picks its own units (the app has no fixed
# roster) — run this fresh whenever a department adds/removes a unit in the
# emm admin UI, and reinstall the result.
#
# Usage: ./gen_sudoers.sh acs.service allta_auth.service my-custom-thing.service
#        ./gen_sudoers.sh acs.service allta_auth.service > /etc/sudoers.d/90-emm-host-control
#        visudo -c -f /etc/sudoers.d/90-emm-host-control
set -euo pipefail

if [[ $# -eq 0 ]]; then
  echo "usage: $0 <unit1.service> [unit2.service ...]" >&2
  exit 1
fi

echo "# sudoers snippet for this department's \"emm-host-control\" account."
echo "# Install as /etc/sudoers.d/90-emm-host-control (mode 0440, owned by root)."
echo "# Regenerated by gen_sudoers.sh — do not hand-edit, rerun the generator"
echo "# instead when the department's unit list changes in the emm admin UI."
echo "#"
echo "# One explicit line per unit x action, NO wildcards — a wildcard rule"
echo "# like \"systemctl * *.service\" would let this account run any"
echo "# systemctl subcommand on any unit, defeating the whole point."
echo

for unit in "$@"; do
  name="${unit%.service}"
  for action in start stop restart; do
    echo "emm-host-control ALL=(root) NOPASSWD: /bin/systemctl ${action} ${name}.service"
  done
done
