"""initial schema action based

Revision ID: d3ad4aac49cc
Revises: 
Create Date: 2026-05-14 14:33:13.883233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3ad4aac49cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('base_frequency_mhz', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cpu_models_architecture'), 'cpu_models', ['architecture'], unique=False)
    op.create_table('entity_permissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('granted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'role', 'action', name='uq_entity_role_action')
    )
    op.create_index(op.f('ix_entity_permissions_entity_type'), 'entity_permissions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_permissions_role'), 'entity_permissions', ['role'], unique=False)
    op.create_table('os_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_versions_name'), 'os_versions', ['name'], unique=True)
    op.create_table('servers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('mgmt_ip_address', postgresql.INET(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('os_version_id', sa.String(length=64), nullable=True),
    sa.Column('os_last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('power_state', sa.String(length=32), nullable=False),
    sa.Column('busy_state', sa.String(length=32), nullable=False),
    sa.Column('busy_user_id', sa.String(length=64), nullable=True),
    sa.Column('busy_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('busy_note', sa.String(length=512), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('asset_tag', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('cpu_id', sa.String(length=64), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('ram_total_mb', sa.Integer(), nullable=True),
    sa.Column('network_interface_name', sa.String(length=64), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['os_version_id'], ['os_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_servers_busy_state_user', 'servers', ['busy_state', 'busy_user_id'], unique=False)
    op.create_index(op.f('ix_servers_busy_user_id'), 'servers', ['busy_user_id'], unique=False)
    op.create_index(op.f('ix_servers_cpu_id'), 'servers', ['cpu_id'], unique=False)
    op.create_index(op.f('ix_servers_department_id'), 'servers', ['department_id'], unique=False)
    op.create_index('ix_servers_department_status', 'servers', ['department_id', 'status'], unique=False)
    op.create_index(op.f('ix_servers_ip_address'), 'servers', ['ip_address'], unique=True)
    op.create_index(op.f('ix_servers_os_version_id'), 'servers', ['os_version_id'], unique=False)
    op.create_table('ipmi_controllers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('password_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_table('server_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('password_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_sudo', sa.Boolean(), nullable=False),
    sa.Column('unix_groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('linked_user_id', sa.String(length=64), nullable=True),
    sa.Column('shell', sa.String(length=64), nullable=True),
    sa.Column('home_dir', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'login', name='uq_server_account_login')
    )
    op.create_index(op.f('ix_server_accounts_linked_user_id'), 'server_accounts', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_server_accounts_server_id'), 'server_accounts', ['server_id'], unique=False)
    op.create_table('server_disks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'device_name', name='uq_server_disk_device')
    )
    op.create_index(op.f('ix_server_disks_server_id'), 'server_disks', ['server_id'], unique=False)
    op.create_index('uq_server_system_disk', 'server_disks', ['server_id'], unique=True, postgresql_where='is_system')
    op.create_table('server_installed_packages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name', 'source', name='uq_installed_package_server_name_source')
    )
    op.create_index('ix_installed_package_name', 'server_installed_packages', ['name'], unique=False)
    op.create_index(op.f('ix_server_installed_packages_server_id'), 'server_installed_packages', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_installed_packages_server_id'), table_name='server_installed_packages')
    op.drop_index('ix_installed_package_name', table_name='server_installed_packages')
    op.drop_table('server_installed_packages')
    op.drop_index('uq_server_system_disk', table_name='server_disks', postgresql_where='is_system')
    op.drop_index(op.f('ix_server_disks_server_id'), table_name='server_disks')
    op.drop_table('server_disks')
    op.drop_index(op.f('ix_server_accounts_server_id'), table_name='server_accounts')
    op.drop_index(op.f('ix_server_accounts_linked_user_id'), table_name='server_accounts')
    op.drop_table('server_accounts')
    op.drop_table('ipmi_controllers')
    op.drop_index(op.f('ix_servers_os_version_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_ip_address'), table_name='servers')
    op.drop_index('ix_servers_department_status', table_name='servers')
    op.drop_index(op.f('ix_servers_department_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_cpu_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_busy_user_id'), table_name='servers')
    op.drop_index('ix_servers_busy_state_user', table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_os_versions_name'), table_name='os_versions')
    op.drop_table('os_versions')
    op.drop_index(op.f('ix_entity_permissions_role'), table_name='entity_permissions')
    op.drop_index(op.f('ix_entity_permissions_entity_type'), table_name='entity_permissions')
    op.drop_table('entity_permissions')
    op.drop_index(op.f('ix_cpu_models_architecture'), table_name='cpu_models')
    op.drop_table('cpu_models')
    # ### end Alembic commands ###
