# проксирование /api/auth → allta-auth-api
location /api/auth/ {
    # чтобы FastAPI с root_path="/api/auth" правильно строил URL
    proxy_set_header X-Forwarded-Prefix /api/auth;
    # отключаем upstream-сжатие для sub_filter
    proxy_set_header Accept-Encoding    "";

    proxy_pass http://allta_auth_api_upstream/;

    # Swagger-UI: меняем URL JSON-схемы на внешний путь
    sub_filter     '/v1/openapi.json' '/api/auth/v1/openapi.json';
    sub_filter_once on;
}
