# проксирование /api/config → allta-config-api
location /api/config/ {
    # чтобы FastAPI с root_path="/api/config" правильно строил URL
    proxy_set_header X-Forwarded-Prefix /api/config;
    # отключаем upstream-сжатие для sub_filter
    proxy_set_header Accept-Encoding    "";

    proxy_pass http://allta_config_api_upstream/;

    # Swagger-UI: меняем URL JSON-схемы на внешний путь
    sub_filter     '/v1/openapi.json' '/api/config/v1/openapi.json';
    sub_filter_once on;
}
