- block:
    - name: Remove virtual network
      shell:
        cmd: vboxmanage hostonlyif remove {{ vbox_hostonly_ifname }}

    - name: Clear variable
      set_fact:
        vbox_hostonly_ifname: ''
  when: virtual_network.recreate and vbox_hostonly_ifname != ''

- block:
    - name: Create host-only network
      shell:
        cmd: vboxmanage hostonlyif create | awk '{print $2}' | tr -d "'"
      register: hostonly_ifname

    - name: Save ifname
      set_fact:
        vbox_hostonly_ifname: "{{ hostonly_ifname.stdout }}"
  when: vbox_hostonly_ifname == ''

- name: Configure host-only network
  shell: |
    vboxmanage hostonlyif ipconfig {{ vbox_hostonly_ifname }} --ip {{ astra_network_ip }}.1
    vboxmanage dhcpserver add --ifname {{ vbox_hostonly_ifname }} --ip {{ astra_network_ip }}.1 \
               --netmask 255.255.255.0 --lowerip {{ astra_network_ip }}.10 --upperip {{ astra_network_ip }}.20
    vboxmanage dhcpserver modify --ifname {{ vbox_hostonly_ifname }} --enable