- name: Install necessary components
  apt:
    name:
      - apache2
      - libpq-dev
      - "{{ 'libapache2-mod-auth-gssapi' if debian_linux
            else 'libapache2-mod-auth-kerb' }}"
      - libapache2-mod-wsgi-py3
      - python3-psycopg2
      - python3-django
      - python3-flask
      - php
      - php-common
      - php-pgsql
      - libreoffice-calc{{ '-nogui' if debian_linux else '' }}
      - libreoffice-writer{{ '-nogui' if debian_linux else '' }}
  register: result
  until: result is not failed

- name: Rsync contrprimer files
  synchronize:
    src: contrprimer/               # all files
    dest: /var/www/html/contrprimer # into that folder
    recursive: yes
    archive: no
    use_ssh_args: yes

- name: Set permissions for contrprimer files
  file:
    path: /var/www/html/contrprimer
    owner: '{{ ansible_ssh_user }}'
    group: www-data
    mode: u=rwx,g=rx,o=rx
    recurse: yes

- name: Set owner of /var/www to local admin
  file:
    path: /var/www
    owner: '{{ ansible_ssh_user }}'

- name: Configure Debian
  include_tasks: debian.yml
  when: debian_linux

- name: Set database connection string environment variable for Apache
  lineinfile:
    path: /etc/apache2/envvars
    regexp: '^export CONTRPRIMER_DB_CONNECT=".*"\n'
    line: >-
      export CONTRPRIMER_DB_CONNECT="dbname={{ server.pg.db_name }}
      host={{ (hostvars[groups.load_balancers_db.0].virtual_domain_name if server.pg.load_balancing.enabled
               else hostvars[groups.databases.0].domain_name) + '.' + astra_domain }} port={{ server.pg.port }}"

- name: Set django allowed hosts
  lineinfile:
    path: /var/www/html/contrprimer/contrprimer_django/__init__.py
    regexp: "(.*)ALLOWED_HOSTS.*'.*'.*\n"
    backrefs: yes
    line: \1ALLOWED_HOSTS=['.{{ astra_domain }}'],

- name: Configure Apache
  import_tasks: configure.yml

# Only restart service and do not reboot a machine
- block:
    - service:
        name: apache2
        state: started
      check_mode: yes
      register: apache2

    - name: Set signal to restart web server
      set_fact:
        restart_web_server: '{{ not apache2.changed }}'
