"""add fix deps

Revision ID: 1d52ad4aac43
Revises: 454b3dc53645
Create Date: 2025-08-28 12:33:08.054160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d52ad4aac43'
down_revision: Union[str, Sequence[str], None] = '454b3dc53645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('password_enc', sa.String(), nullable=True))
    op.alter_column('vm', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('vm', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               nullable=True)
    op.drop_constraint(op.f('vm_name_key'), 'vm', type_='unique')
    op.create_index(op.f('ix_vm_name'), 'vm', ['name'], unique=True)
    op.create_index(op.f('ix_vm_status'), 'vm', ['status'], unique=False)
    op.create_unique_constraint('uq_vm_snapshot_vm_id_name', 'vm_snapshots', ['vm_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vm_snapshot_vm_id_name', 'vm_snapshots', type_='unique')
    op.drop_index(op.f('ix_vm_status'), table_name='vm')
    op.drop_index(op.f('ix_vm_name'), table_name='vm')
    op.create_unique_constraint(op.f('vm_name_key'), 'vm', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('vm', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vm', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('vm', 'password_enc')
    # ### end Alembic commands ###
