"""add vm.server_id

Revision ID: 454b3dc53645
Revises: d92f9eae32ce
Create Date: 2025-08-13 14:08:55.237882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454b3dc53645'
down_revision: Union[str, Sequence[str], None] = 'd92f9eae32ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm', sa.Column('server_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_vm_server_id'), 'vm', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_server_id'), table_name='vm')
    op.drop_column('vm', 'server_id')
    # ### end Alembic commands ###
