"""initial schema

Revision ID: ca02fc0dc997
Revises: 
Create Date: 2025-08-13 11:34:26.265330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca02fc0dc997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название диапазона'),
    sa.Column('ip_start', postgresql.INET(), nullable=False, comment='Начало диапазона'),
    sa.Column('ip_end', postgresql.INET(), nullable=False, comment='Конец диапазона'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ip_ranges_id'), 'ip_ranges', ['id'], unique=False)
    op.create_table('vm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('ram', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('kernel', sa.String(length=100), nullable=False),
    sa.Column('occupied_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vm_id'), 'vm', ['id'], unique=False)
    op.create_table('vm_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_snapshots_id'), 'vm_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_snapshots_id'), table_name='vm_snapshots')
    op.drop_table('vm_snapshots')
    op.drop_index(op.f('ix_vm_id'), table_name='vm')
    op.drop_table('vm')
    op.drop_index(op.f('ix_ip_ranges_id'), table_name='ip_ranges')
    op.drop_table('ip_ranges')
    # ### end Alembic commands ###
