FROM python:3.12-slim

WORKDIR /git

ARG DEBIAN_FRONTEND=noninteractive

# Установка devpi-server, devpi-web (для веб-интерфейса) и devpi-client
RUN pip install --no-cache-dir devpi-server devpi-web devpi-client sphinx itcase_sphinx_theme 
RUN apt update && apt install git curl wget -y

# Открываем порт 3141 (используется как для API, так и для веб-интерфейса)
EXPOSE 3141

ARG DEVPI_USER
ARG DEVPI_PASSWORD
ARG DEVPI_ADMIN_PASSWORD

# Создаем директорию для данных
RUN mkdir -p /data
RUN mkdir /health
# Инициализация devpi-сервера
RUN devpi-init --serverdir /data --root-passwd=${DEVPI_ADMIN_PASSWORD}

# Устанавливаем переменную окружения для использования devpi-client
ENV DEVPISERVER_SERVERDIR=/data

# Запускаем devpi-сервер в фоне, проводим начальную настройку и завершаем его
RUN (devpi-server --host 0.0.0.0 --port 3141 --serverdir /data &) && \
    sleep 15 && \
    devpi use http://localhost:3141 && \
    devpi login root --password=${DEVPI_ADMIN_PASSWORD} && \
    devpi use root/pypi && \
    # devpi index -c releases bases=root/pypi mirror_whitelist=* && 
    devpi user -c ${DEVPI_USER} password=${DEVPI_PASSWORD} && \
    devpi login ${DEVPI_USER} --password=${DEVPI_PASSWORD} && \
    devpi index -c dev bases=root/pypi mirror_whitelist=\* 
    
RUN kill -TERM 1

COPY ./template/new_release.py /git/
COPY ./template/health_checker.sh /health/
# При старте контейнера запускается devpi-сервер с включенным веб-интерфейсом (доступным по http://localhost:3141)
CMD ["sh", "-c", "(devpi-server --host 0.0.0.0 --port 3141 --serverdir /data --outside-url $DEVPI_URL &) && sleep 10 && python3 new_release.py"]
