version: "3.9"

services:
  loging_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loging_service
    environment:
      APP_ENV: local
      APP_HOST: 0.0.0.0
      APP_PORT: 8001
      DATABASE_URL: postgresql+psycopg://logging_user:logging_password@logging_postgres:5432/logging_db
      SERVICE_API_KEYS: '{"auth_service":"change-me-auth-service-key","server_service":"change-me-server-service-key","config_service":"change-me-config-service-key","server_worker":"change-me-server-worker-key"}'
      INTROSPECT_SERVICE_API_KEY: change-me-introspect-key
    ports:
      - "8001:8001"
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      - logging_postgres

  logging_postgres:
    image: postgres:16
    container_name: logging_postgres
    environment:
      POSTGRES_DB: logging_db
      POSTGRES_USER: logging_user
      POSTGRES_PASSWORD: logging_password
    ports:
      - "5433:5432"
    volumes:
      - logging_postgres_data:/var/lib/postgresql/data

volumes:
  logging_postgres_data:
