- block:
    - name: Wait until haproxy freeipa services are created
      vars:
        signal: haproxy_{{ item }}_service
      include_tasks: '{{ playbook_dir }}/tasks/wait_for_file_signal.yml'
      loop: '{{ groups.load_balancers_web }}'
      when: server.apache.load_balancing.enabled and server.apache.wait_for_lb_services

    - name: Remove keytab
      file:
        path: /etc/apache2/http.keytab
        state: absent

    - name: Create keytab for http service
      command: >-
        ipa-getkeytab -s {{ hostvars.domain.domain_name }}.{{ astra_domain }} -k /etc/apache2/http.keytab
                      -p HTTP/{{ hostvars[inventory_hostname].domain_name }}.{{ astra_domain }}

    - name: Retrieve keytab for haproxy service
      command: >-
        ipa-getkeytab -s {{ hostvars.domain.domain_name }}.{{ astra_domain }} -k /etc/apache2/http.keytab
                      --retrieve {% for proxy in groups.load_balancers_web %}
                      -p HTTP/{{ hostvars[proxy].domain_name }}.{{ astra_domain }} {% endfor %}
      when: server.apache.load_balancing.enabled

    - name: Set www-data owner and change mode of keytab
      file:
        path: /etc/apache2/http.keytab
        owner: www-data
        mode: u=rw,g=r,o=r
  when: >-
    (server.apache_postgres_together and inventory_hostname in groups.databases)

- block:
    - name: Create keytab for postgres service
      command: >-
        ipa-getkeytab -s {{ hostvars.domain.domain_name }}.{{ astra_domain }}
                      -k /etc/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}/krb5.keytab
                      -p postgres/{{ hostvars[inventory_hostname].domain_name }}.{{ astra_domain }}

    - name: Set postgres owner of postgres keytab
      file:
        path: /etc/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}/krb5.keytab
        owner: postgres
  when: 'inventory_hostname in groups.databases'

- name: Set uid variable
  set_fact:
    allowed_uid: >-
      {{ "www-data, postgres" if server.apache_postgres_together else
         "postgres" }}

- name: Read sssd.conf
  command: |
    cat /etc/sssd/sssd.conf
  register: sssd
  changed_when: false

- name: Configure sssd.conf (option 'allowed_uids' is not present)
  lineinfile:
    path: /etc/sssd/sssd.conf
    insertafter: '^\[ifp\]\n'
    line: 'allowed_uids = {{ allowed_uid }}'
  when: '"allowed_uids" not in sssd.stdout'

- name: Configure sssd.conf (option 'allowed_uids' is present)
  lineinfile:
    path: /etc/sssd/sssd.conf
    backrefs: yes
    regexp: '^(allowed_uids.*)$'
    line: '\1, {{ allowed_uid }}'
  when: '"allowed_uids" in sssd.stdout and allowed_uid not in sssd.stdout'
