- name: Setup server
  become: yes
  block:
    - name: Setup web server
      include_tasks: apache/main.yml
      when: >-
        inventory_hostname in groups.web_servers or
        (server.apache_postgres_together and inventory_hostname in groups.databases)

    - name: Setup database server
      include_tasks: postgres/main.yml
      when: 'inventory_hostname in groups.databases'

    - name: Wait until domain controller is ready
      vars:
        signal: domain
      import_tasks: '{{ playbook_dir }}/tasks/wait_for_domain.yml'

    - name: Setup freeipa client
      include_role:
        name: domain_client

    - name: Get admin kerberos ticket
      shell: |
        echo {{ domain.admin_password  }} | kinit {{ domain.admin }}
      changed_when: false

    - name: Configure domain
      import_tasks: configure_domain.yml

    - name: Finish setting up contrprimer
      import_tasks: kerberos.yml

    - name: Reboot machines or restart services
      import_tasks: reboot.yml
