- name: Set condition variables
  set_fact:
    db_replication: '{{ server.pg.replication.enabled and inventory_hostname in groups.databases }}'
    db_restart: '{{ restart_database is defined and restart_database and inventory_hostname in groups.databases }}'
    web_restart: '{{ restart_web_server is defined and restart_web_server }}'

- name: Wait until master replica database is restarted
  vars:
    signal: db_master_replica_restart
  import_tasks: '{{ playbook_dir }}/tasks/wait_for_file_signal.yml'
  when: db_replication and inventory_hostname != groups.databases.0

- name: Restart
  block:
    - name: Restart database
      command: pg_ctlcluster {{ server.pg.version }} {{ server.pg.db_name }} restart
      changed_when: false
      when: db_restart

    - name: Restart web server
      service:
        name: apache2
        state: restarted
      when: web_restart

- name: Reboot
  reboot:
    post_reboot_delay: 5
  when: >-
    restart_domain_client is defined or (not db_restart and not web_restart)

- name: Set signal that master replica database has been restarted
  vars:
    signal: db_master_replica_restart
  import_tasks: '{{ playbook_dir }}/tasks/set_file_signal.yml'
  when: db_replication and inventory_hostname == groups.databases.0

- name: Set signal that standby replicas have been restarted
  vars:
    signal: db_standby_replicas_restart
  import_tasks: '{{ playbook_dir }}/tasks/set_file_signal.yml'
  when: db_replication and inventory_hostname != groups.databases.0

- name: Start pgpool2
  delegate_to: '{{ item }}'
  become: true
  service:
    name: pgpool2
    state: started
  loop: '{{ groups.load_balancers_db }}'
  when: >-
    inventory_hostname == groups.databases.0 and
    (db_replication and groups.load_balancers_db.0 not in ansible_play_hosts_all)