"""initial

Revision ID: 3ab7bdfec8d6
Revises: 
Create Date: 2025-06-30 20:34:30.748247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ab7bdfec8d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_os_versions_id'), 'os_versions', ['id'], unique=False)
    op.create_table('physical_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('cpu_total', sa.Integer(), nullable=False),
    sa.Column('ram_total', sa.Integer(), nullable=False),
    sa.Column('virtualization', sa.Boolean(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('admin_user', sa.String(length=100), nullable=False),
    sa.Column('admin_pass_enc', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('os_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['os_version_id'], ['os_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_physical_servers_id'), 'physical_servers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physical_servers_id'), table_name='physical_servers')
    op.drop_table('physical_servers')
    op.drop_index(op.f('ix_os_versions_id'), table_name='os_versions')
    op.drop_table('os_versions')
    # ### end Alembic commands ###
