"""add admin panel ip

Revision ID: 5f16350c05c1
Revises: ddcbe3fe0ebd
Create Date: 2025-07-01 17:16:33.980232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f16350c05c1'
down_revision: Union[str, Sequence[str], None] = 'ddcbe3fe0ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_servers', sa.Column('driver_type', sa.String(length=10), nullable=False, comment='ilo или idrac'))
    op.add_column('physical_servers', sa.Column('admin_panel_ip', postgresql.INET(), nullable=False))
    op.alter_column('physical_servers', 'admin_panel_user',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Логин в панель управления',
               existing_nullable=False)
    op.alter_column('physical_servers', 'admin_panel_pass',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Пароль в панель управления',
               existing_nullable=False)
    op.drop_column('physical_servers', 'server_user')
    op.drop_column('physical_servers', 'server_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_servers', sa.Column('server_password', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Пароль пользователя на сервере'))
    op.add_column('physical_servers', sa.Column('server_user', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Имя пользователя на сервере'))
    op.alter_column('physical_servers', 'admin_panel_pass',
               existing_type=sa.VARCHAR(),
               comment='Пароль в панель управления',
               existing_nullable=False)
    op.alter_column('physical_servers', 'admin_panel_user',
               existing_type=sa.VARCHAR(length=100),
               comment='Логин в панель управления',
               existing_nullable=False)
    op.drop_column('physical_servers', 'admin_panel_ip')
    op.drop_column('physical_servers', 'driver_type')
    # ### end Alembic commands ###
