"""add server.phu_if

Revision ID: d4e7ccc2ce2f
Revises: 83ae28338653
Create Date: 2025-08-15 17:18:38.825448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e7ccc2ce2f'
down_revision: Union[str, Sequence[str], None] = '83ae28338653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_servers', sa.Column('phy_if', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('physical_servers', 'phy_if')
    # ### end Alembic commands ###
