"""add admin_panel_user

Revision ID: ddcbe3fe0ebd
Revises: 3ab7bdfec8d6
Create Date: 2025-07-01 14:06:06.261609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcbe3fe0ebd'
down_revision: Union[str, Sequence[str], None] = '3ab7bdfec8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_servers', sa.Column('server_user', sa.String(length=100), nullable=False, comment='Имя пользователя на сервере'))
    op.add_column('physical_servers', sa.Column('server_password', sa.String(), nullable=False, comment='Пароль пользователя на сервере'))
    op.add_column('physical_servers', sa.Column('admin_panel_user', sa.String(length=100), nullable=False, comment='Логин в панель управления'))
    op.add_column('physical_servers', sa.Column('admin_panel_pass', sa.String(), nullable=False, comment='Пароль в панель управления'))
    op.drop_column('physical_servers', 'admin_pass_enc')
    op.drop_column('physical_servers', 'admin_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physical_servers', sa.Column('admin_user', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('physical_servers', sa.Column('admin_pass_enc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('physical_servers', 'admin_panel_pass')
    op.drop_column('physical_servers', 'admin_panel_user')
    op.drop_column('physical_servers', 'server_password')
    op.drop_column('physical_servers', 'server_user')
    # ### end Alembic commands ###
