{
 "title": "ALLTA dashboard",
 "tags": [
  "linux",
  "astralinux"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Server",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme.*|[a-z]+|mmcblk[0-9]+"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU usage（30s）",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30s])) * 100)"
    }
   ]
  },
  {
   "title": "RAM information",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Memory_Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "Memory_Cached"
    }
   ]
  },
  {
   "title": "CPU usage（%）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) + avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average system load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Audit number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait（30s）",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30s])) * 100"
    }
   ]
  },
  {
   "title": "Total disk space",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node\", fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM information",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Memory_Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "Memory_Cached"
    }
   ]
  },
  {
   "title": "Hardware temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Currently open file descriptor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * irate(node_disk_io_time_seconds_total{instance=\"$node\", job=\"$job\", device=~\"$diskdevices\"}[$__rate_interval])\r\nunless\r\n(node_disk_io_time_seconds_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_io_time_seconds_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "I/O Usage read / write (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])\r\nunless\r\n(node_disk_read_bytes_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_read_bytes_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])\r\nunless\r\n(node_disk_written_bytes_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_written_bytes_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk IO read / write (time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}[1m])\r\nunless\r\n(node_disk_io_time_seconds_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_io_time_seconds_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}[1m])\r\nunless\r\n(node_disk_read_time_seconds_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_read_time_seconds_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}[1m])\r\nunless\r\n(node_disk_write_time_seconds_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_write_time_seconds_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out upload"
    }
   ]
  },
  {
   "title": "Disk read / write rate（IOPS）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}[1m])\r\nunless\r\n(node_disk_reads_completed_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_reads_completed_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])\r\nunless\r\n(node_disk_writes_completed_total{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_writes_completed_total{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}_write"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}\r\nunless\r\n(node_disk_io_now{instance=\"10.177.103.204:9100\", device=\"nvme0n1\"} OR node_disk_io_now{instance=\"10.177.103.205:9100\", device=\"nvme0n1\"})",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}