# group_of_hosts - список хостов, на которые нужно отправить публичный ssh ключ

- become: yes
  block:
    - name: Install sshpass
      apt:
        name: sshpass

    - name: Create /root/.ssh folder
      file:
        path: /root/.ssh
        state: directory

    - name: Create keys
      command: |
        ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
      args:
        creates: /root/.ssh/id_rsa.pub

    - name: Add keys to ssh agent
      shell:
        cmd: eval `ssh-agent -s` && ssh-add /root/.ssh/id_rsa

    - name: Read public key
      command: |
        cat /root/.ssh/id_rsa.pub
      register: pub_key
      changed_when: false

    - name: Copy public key to other hosts
      delegate_to: '{{ item }}'
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: '{{ pub_key.stdout }}'
        mode: 600
      loop: '{{ group_of_hosts | difference([inventory_hostname]) }}'
