# - name: Collect hostnames and IPs
#   set_fact:
#     host_entries: |
#       {% for host in groups['all'] %}
#       {{ hostvars[host]['ansible_host'] }} {{ host }} {{ hostvars[host].get('domain_name', '') }}
#       {% endfor %}

# - name: Update /etc/hosts
#   become: true
#   lineinfile:
#     path: /etc/hosts
#     line: "{{ item }}"
#     state: present
#   loop: "{{ host_entries.split('\n') }}"
#   when: item | trim != ""


- name: Update /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: |
      10.177.5.111    qa111.devos.astralinux.ru
      10.177.43.1    releases.devos.astralinux.ru
      127.0.0.1   localhost
      {{ hostvars['domain']['ansible_host'] }} {{ hostvars['domain']['domain_name'] }}.{{ astra_domain }} {{ hostvars['domain']['domain_name'] }}
      {{ hostvars['database']['ansible_host'] }} {{ hostvars['database']['domain_name'] }}.{{ astra_domain }} {{ hostvars['database']['domain_name'] }}
      {{ hostvars['database_2']['ansible_host'] }} {{ hostvars['database_2']['domain_name'] }}.{{ astra_domain }} {{ hostvars['database_2']['domain_name'] }}
      {{ hostvars['database_3']['ansible_host'] }} {{ hostvars['database_3']['domain_name'] }}.{{ astra_domain }} {{ hostvars['database_3']['domain_name'] }}
      {{ hostvars['lb_db']['ansible_host'] }} {{ hostvars['lb_db']['domain_name'] }}.{{ astra_domain }} {{ hostvars['lb_db']['domain_name'] }}
      {{ hostvars['lb_db_2']['ansible_host'] }} {{ hostvars['lb_db_2']['domain_name'] }}.{{ astra_domain }} {{ hostvars['lb_db_2']['domain_name'] }}
      {{ hostvars['lb_db_3']['ansible_host'] }} {{ hostvars['lb_db_3']['domain_name'] }}.{{ astra_domain }} {{ hostvars['lb_db_3']['domain_name'] }}






     