- name: Collect hostnames and IPs
  set_fact:
    host_entries: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] }} {{ host }} {{ hostvars[host].get('domain_name', '') }}
      {% endfor %}

- name: Update /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop: "{{ host_entries.split('\n') }}"
  when: item | trim != ""