# Настройки серверного имени
ServerRoot "/usr/local/apache2"
Listen 80
ServerName localhost

# Указываем, где находятся остальные конфигурационные файлы
IncludeOptional conf/extra/httpd-vhosts.conf

# Указываем путь к логам
ErrorLog logs/error_log
LogLevel warn
CustomLog logs/access_log combined

# Указываем настройки модулей
LoadModule log_config_module modules/mod_log_config.so
LoadModule mpm_event_module modules/mod_mpm_event.so
Include conf/extra/web_app.conf
LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule rewrite_module modules/mod_rewrite.so

# Включаем возможность использования дополнительных конфигурационных файлов
IncludeOptional conf/extra/*.conf

# Дополнительные настройки для безопасности и производительности
Timeout 120
KeepAlive On
MaxKeepAliveRequests 2000
KeepAliveTimeout 15
