
FROM nginx:alpine

RUN apk add --no-cache apache2-utils

# Update the base image to ensure all packages are up-to-date
RUN apk update && apk upgrade --no-cache


RUN rm /etc/nginx/conf.d/default.conf
RUN mkdir -p /etc/nginx/services

COPY template/nginx.conf /etc/nginx/nginx.conf
COPY template/conf.d/* /etc/nginx/conf.d/
COPY template/services/* /etc/nginx/services/
COPY template/html /etc/nginx/html

# Expose HTTP port
EXPOSE 80

# Launch Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
