"""Каталог audit-событий, которые эмитит testing_service.

Регистрируется в loging_service на startup через `register_events()`.
Инфраструктурные события (lifecycle + HTTP middleware) плюс те бизнес-события,
чей домен уже реализован. Остальные (`test.launch`/`test.cancel`/
`stp.status_updated`/...) добавляются вместе с доменом, который их производит.

Имя действия — `<object>.<verb>` (`global_variable.create`), как в остальных
сервисах emm.
"""

from __future__ import annotations

import logging

import httpx

from src.core.config import get_settings
from src.core.constants import SERVICE_NAME as _SERVICE_NAME
from src.core.http import bearer_header

logger = logging.getLogger("audit")

SERVICE_EVENTS = [
    {"action": "service.started", "description": "Service started up", "default_severity": "INFO"},
    {"action": "http.access_denied", "description": "HTTP 401/403 response", "default_severity": "CRITICAL"},
    {"action": "http.client_error", "description": "HTTP 4xx response (except 401/403)", "default_severity": "WARNING"},
    {"action": "http.server_error", "description": "HTTP 5xx response", "default_severity": "CRITICAL"},
    {"action": "global_variable.create", "description": "Global variable created", "default_severity": "INFO"},
    {"action": "global_variable.update", "description": "Global variable updated", "default_severity": "INFO"},
    {"action": "global_variable.delete", "description": "Global variable deleted", "default_severity": "WARNING"},
    {"action": "test_definition.create", "description": "Test definition created", "default_severity": "INFO"},
    {"action": "test_definition.update", "description": "Test definition updated", "default_severity": "INFO"},
    {"action": "test_definition.delete", "description": "Test definition deleted", "default_severity": "WARNING"},
    {"action": "test_definition.launch_preview", "description": "Launch job preview built for a test (secrets revealed in-memory, masked in response)", "default_severity": "INFO"},
    {"action": "test_command_arg.copy", "description": "Command parameters copied from another test", "default_severity": "INFO"},
    {"action": "test_command_arg.create", "description": "Test command arg slot added", "default_severity": "INFO"},
    {"action": "test_command_arg.update", "description": "Test command arg slot updated", "default_severity": "INFO"},
    {"action": "test_command_arg.delete", "description": "Test command arg slot removed", "default_severity": "INFO"},
    {"action": "test_step.create", "description": "Step added to a multi-step test", "default_severity": "INFO"},
    {"action": "test_step.update", "description": "Test step changed (name, suffix, run mode, stand setup)", "default_severity": "INFO"},
    {"action": "test_step.delete", "description": "Test step removed with its command slots", "default_severity": "WARNING"},
    {"action": "test_step.reorder", "description": "Steps of a multi-step test were reordered", "default_severity": "INFO"},
    {"action": "queue_item.step_completed", "description": "A step of a multi-step test finished; the queue item moves to the next step", "default_severity": "INFO"},
    {"action": "queue_item.stand_setup_requested", "description": "Stand setup without restore requested from server_service before the next test step", "default_severity": "INFO"},
    {"action": "test_stand.create", "description": "Test stand registered", "default_severity": "INFO"},
    {"action": "test_stand.update", "description": "Test stand updated", "default_severity": "INFO"},
    {"action": "test_stand.delete", "description": "Test stand deleted", "default_severity": "WARNING"},
    {"action": "test_stand.test_credentials_viewed", "description": "Test stand's test-user credentials card opened via server_service proxy (reveal=false) — metadata only, no secret in the response", "default_severity": "WARNING"},
    {"action": "test_stand.test_credentials_revealed", "description": "Test stand's test-user password and SSH private key revealed via server_service proxy (reveal=true)", "default_severity": "CRITICAL"},
    {"action": "department_test_settings.update", "description": "Department test settings upserted", "default_severity": "INFO"},
    {"action": "department_test_account.update", "description": "Department test account (login/password/SSH key in secret_service) created or changed", "default_severity": "WARNING"},
    {"action": "queue_item.launch_rejected", "description": "Queued test no longer allows a normal launch", "default_severity": "WARNING"},
    {"action": "queue_item.enqueued", "description": "Test queued on a stand", "default_severity": "INFO"},
    {"action": "queue_item.prepare_requested", "description": "prepare-for-test requested from server_service", "default_severity": "INFO"},
    {"action": "queue_item.prepare_start_failed", "description": "Could not start the preparation cycle (acquire/prepare-for-test call failed)", "default_severity": "WARNING"},
    {"action": "queue_item.ready", "description": "prepare-for-test callback succeeded, credentials stashed", "default_severity": "INFO"},
    {"action": "queue_item.prepare_failed", "description": "prepare-for-test callback reported failure", "default_severity": "WARNING"},
    {"action": "queue_item.retry_created", "description": "A retry queue item was created after a failure", "default_severity": "INFO"},
    {"action": "queue_item.claimed", "description": "testing_worker claimed a ready queue item", "default_severity": "INFO"},
    {"action": "queue_item.completed", "description": "testing_worker reported the outcome of an SSH run", "default_severity": "INFO"},
    {"action": "queue_item.awaiting_verdict", "description": "SSH run finished; the stand stays held while the test's status is read from Zephyr", "default_severity": "INFO"},
    {"action": "queue_item.verdict_resolved", "description": "Test verdict read from Zephyr (or the wait timed out)", "default_severity": "INFO"},
    {"action": "provisioning_profile.create", "description": "Provisioning profile created", "default_severity": "WARNING"},
    {"action": "scenario.create", "description": "Multi-stand scenario created", "default_severity": "INFO"},
    {"action": "scenario.update", "description": "Multi-stand scenario replaced (fields, stands, actions)", "default_severity": "INFO"},
    {"action": "scenario.delete", "description": "Multi-stand scenario deleted", "default_severity": "WARNING"},
    {"action": "scenario.preview", "description": "Scenario preview built (per-action launch jobs, secrets masked)", "default_severity": "INFO"},
    {"action": "scenario_run.started", "description": "Scenario run started (all-or-nothing stand reservation follows)", "default_severity": "INFO"},
    {"action": "scenario_run.waiting_for_stands", "description": "Scenario run waits: some stands are busy; taken reservations released", "default_severity": "INFO"},
    {"action": "scenario_run.stands_acquired", "description": "Scenario run holds all its stands; preparation started", "default_severity": "INFO"},
    {"action": "scenario_run.stop_requested", "description": "Scenario run stop requested", "default_severity": "WARNING"},
    {"action": "scenario_run.succeeded", "description": "Scenario run finished, all verdict actions passed", "default_severity": "INFO"},
    {"action": "scenario_run.failed", "description": "Scenario run failed (preparation, a non-verdict action or the verdict)", "default_severity": "WARNING"},
    {"action": "scenario_run.stopped", "description": "Scenario run stopped; stands released", "default_severity": "WARNING"},
    {"action": "provisioning_profile.update", "description": "Provisioning profile changed", "default_severity": "WARNING"},
    {"action": "stand_setup.completed", "description": "server_service reported the outcome of a stand setup without restore", "default_severity": "INFO"},
    {"action": "launch_profile.create", "description": "Launch profile created", "default_severity": "WARNING"},
    {"action": "launch_profile.update", "description": "Launch profile renamed or made default", "default_severity": "WARNING"},
    {"action": "launch_profile.version_created", "description": "New launch profile version (starter.sh, paths, commands) became current", "default_severity": "WARNING"},
    {"action": "zephyr_status_mapping.update", "description": "Department Zephyr status → test outcome mapping replaced", "default_severity": "INFO"},
    {"action": "zephyr_status_mapping.reset", "description": "Department Zephyr status mapping reset to the default set", "default_severity": "INFO"},
    {"action": "queue_item.interrupt_requested", "description": "Skip/pause requested for a queue item that is running on a stand", "default_severity": "WARNING"},
    {"action": "queue_item.skipped", "description": "Queue item was skipped; the stand moves on to the next one", "default_severity": "WARNING"},
    {"action": "queue_item.paused", "description": "Queue item was paused; the stand waits for an explicit resume", "default_severity": "WARNING"},
    {"action": "queue_item.resumed", "description": "Paused queue item was put back at the end of the stand queue", "default_severity": "INFO"},
    {"action": "queue_item.delete", "description": "Queue item removed from the queue entirely (no terminal record left)", "default_severity": "WARNING"},
    {"action": "queue.force_takeover", "description": "Stand reservation taken over from its holder by an admin force launch (or the attempt was denied/impossible)", "default_severity": "WARNING"},
    {"action": "queue.replace", "description": "Stand queue replaced by an admin: queued items removed and the running test interrupted", "default_severity": "WARNING"},
    {"action": "test_stand.queue_cleared", "description": "All not-yet-started queue items were removed from a stand's queue", "default_severity": "WARNING"},
    {"action": "test_stand.queue_retry_failed", "description": "All eligible failed queue items of a stand were retried in one call", "default_severity": "INFO"},
    {"action": "test_stand.queue_reordered", "description": "Not-yet-started queue items of a stand were manually reordered", "default_severity": "INFO"},
    {"action": "test_log.rotated", "description": "A test log was deleted by the retention policy", "default_severity": "WARNING"},
    {"action": "test_run.create", "description": "A fleet-wide test run campaign was created", "default_severity": "INFO"},
    {"action": "test_run.status_changed", "description": "A test run campaign's aggregate status changed after a queue item transition", "default_severity": "INFO"},
    {"action": "stp_test_case.create", "description": "STP test case (Zephyr mirror) created", "default_severity": "INFO"},
    {"action": "stp_test_case.update", "description": "STP test case updated", "default_severity": "INFO"},
    {"action": "stp_test_case.delete", "description": "STP test case deleted", "default_severity": "WARNING"},
    {"action": "stp_test_run.generate", "description": "STP test runs generated in Zephyr for a department/RC/mode/kernel", "default_severity": "INFO"},
    {"action": "stp_cell.auto_updated", "description": "STP cell status updated automatically from a queue item transition", "default_severity": "INFO"},
    {"action": "stp_cell.manual_override", "description": "STP cell status overridden manually (not synced to Zephyr)", "default_severity": "WARNING"},
    {"action": "department_integration_settings.update", "description": "Department Jira/Zephyr/Confluence integration settings upserted", "default_severity": "INFO"},
    {"action": "zephyr_folder.update", "description": "Zephyr folder id of a department/RC set manually", "default_severity": "INFO"},
    {"action": "zephyr_folder.refresh", "description": "Zephyr folder of a department/RC looked up again (find or create)", "default_severity": "INFO"},
    {"action": "run_summary_comment.posted", "description": "End-of-run Confluence blog comment posted/updated/skipped/failed for a test run campaign", "default_severity": "INFO"},
    {"action": "department_report_member.create", "description": "Department report member added", "default_severity": "INFO"},
    {"action": "department_report_member.update", "description": "Department report member updated", "default_severity": "INFO"},
    {"action": "department_report_member.delete", "description": "Department report member removed", "default_severity": "WARNING"},
    {"action": "department_activity_report.generate", "description": "Department activity report generation attempted (manual trigger)", "default_severity": "INFO"},
    {"action": "permission.grant", "description": "entity_permission row granted", "default_severity": "CRITICAL"},
    {"action": "permission.revoke", "description": "entity_permission row revoked", "default_severity": "CRITICAL"},
    {"action": "statistics_settings.update", "description": "Platform statistics service settings upserted", "default_severity": "INFO"},
    {"action": "statistics_recalc.triggered", "description": "Statistics recalculation manually triggered", "default_severity": "INFO"},
    {"action": "statistics_recalc.completed", "description": "Background statistics recalculation finished (succeeded or failed)", "default_severity": "INFO"},
    {"action": "statistics_category.create", "description": "Statistics category added to the recalculation catalog", "default_severity": "INFO"},
    {"action": "statistics_category.update", "description": "Statistics category in the recalculation catalog updated", "default_severity": "INFO"},
    {"action": "statistics_category.delete", "description": "Statistics category removed from the recalculation catalog", "default_severity": "WARNING"},
    {"action": "legacy_compat.department_resolved", "description": "Public /rest/api integration URL: department chosen by the source IP (stand or default) and why", "default_severity": "INFO"},
    {"action": "compat_network.create", "description": "Network allowed to call the public /rest/api compat without authentication", "default_severity": "WARNING"},
    {"action": "compat_network.update", "description": "Allowed network of the public /rest/api compat changed", "default_severity": "WARNING"},
    {"action": "compat_network.delete", "description": "Allowed network of the public /rest/api compat removed", "default_severity": "WARNING"},
    {"action": "legacy_compat_settings.update", "description": "Default department of the public /rest/api compat changed", "default_severity": "INFO"},
]

_DEFAULT_SEVERITY: dict[tuple[str, str], str] = {
    ("service.started", "success"): "INFO",
    # `AuditAccessMiddleware` эмитит 401/403 со статусом `denied`, а не
    # `failure` — без этой пары каждый отказ доступа уезжал в loging с
    # severity=None (AUDIT_EVENTS.md при этом обещает CRITICAL).
    ("http.access_denied", "denied"): "CRITICAL",
    ("http.access_denied", "failure"): "CRITICAL",
    ("http.client_error", "failure"): "WARNING",
    ("http.server_error", "failure"): "CRITICAL",
    ("global_variable.create", "success"): "INFO",
    ("global_variable.create", "failure"): "WARNING",
    ("global_variable.create", "denied"): "WARNING",
    ("global_variable.update", "success"): "INFO",
    ("global_variable.update", "failure"): "WARNING",
    ("global_variable.update", "denied"): "WARNING",
    ("global_variable.delete", "success"): "WARNING",
    ("global_variable.delete", "failure"): "WARNING",
    ("global_variable.delete", "denied"): "WARNING",
    ("test_definition.create", "success"): "INFO",
    ("test_definition.create", "failure"): "WARNING",
    ("test_definition.create", "denied"): "WARNING",
    ("test_definition.update", "success"): "INFO",
    ("test_definition.update", "failure"): "WARNING",
    ("test_definition.update", "denied"): "WARNING",
    ("test_definition.delete", "success"): "WARNING",
    ("test_definition.delete", "failure"): "WARNING",
    ("test_definition.delete", "denied"): "WARNING",
    ("test_definition.launch_preview", "success"): "INFO",
    ("test_command_arg.copy", "success"): "INFO",
    ("test_command_arg.copy", "failure"): "WARNING",
    ("test_command_arg.copy", "denied"): "WARNING",
    ("test_command_arg.create", "success"): "INFO",
    ("test_command_arg.create", "failure"): "WARNING",
    ("test_command_arg.create", "denied"): "WARNING",
    ("test_command_arg.update", "success"): "INFO",
    ("test_command_arg.update", "failure"): "WARNING",
    ("test_command_arg.update", "denied"): "WARNING",
    ("test_command_arg.delete", "success"): "INFO",
    ("test_command_arg.delete", "failure"): "WARNING",
    ("test_command_arg.delete", "denied"): "WARNING",
    ("test_step.create", "success"): "INFO",
    ("test_step.create", "denied"): "WARNING",
    ("test_step.update", "success"): "INFO",
    ("test_step.update", "denied"): "WARNING",
    ("test_step.delete", "success"): "WARNING",
    ("test_step.delete", "denied"): "WARNING",
    ("test_step.reorder", "success"): "INFO",
    ("test_step.reorder", "denied"): "WARNING",
    ("queue_item.step_completed", "success"): "INFO",
    ("queue_item.stand_setup_requested", "success"): "INFO",
    ("test_stand.create", "success"): "INFO",
    ("test_stand.create", "failure"): "WARNING",
    ("test_stand.create", "denied"): "WARNING",
    ("test_stand.update", "success"): "INFO",
    ("test_stand.update", "failure"): "WARNING",
    ("test_stand.update", "denied"): "WARNING",
    ("test_stand.delete", "success"): "WARNING",
    ("test_stand.delete", "failure"): "WARNING",
    ("test_stand.delete", "denied"): "WARNING",
    ("test_stand.test_credentials_viewed", "success"): "WARNING",
    ("test_stand.test_credentials_viewed", "denied"): "WARNING",
    # Раскрытие секрета — отдельное действие с CRITICAL, как
    # `server.test_credentials_revealed` в server_service. denied оставлен
    # WARNING: попытка, отбитая матрицей, секрета не раскрыла.
    ("test_stand.test_credentials_revealed", "success"): "CRITICAL",
    ("test_stand.test_credentials_revealed", "denied"): "WARNING",
    ("department_test_settings.update", "success"): "INFO",
    ("department_test_settings.update", "denied"): "WARNING",
    ("department_test_account.update", "success"): "WARNING",
    ("department_test_account.update", "failure"): "WARNING",
    ("department_test_account.update", "denied"): "WARNING",
    ("queue_item.launch_rejected", "denied"): "WARNING",
    ("queue_item.enqueued", "success"): "INFO",
    ("queue_item.prepare_requested", "success"): "INFO",
    ("queue_item.prepare_start_failed", "failure"): "WARNING",
    ("queue_item.ready", "success"): "INFO",
    ("queue_item.prepare_failed", "failure"): "WARNING",
    ("queue_item.retry_created", "success"): "INFO",
    ("queue_item.claimed", "success"): "INFO",
    ("queue_item.completed", "success"): "INFO",
    ("queue_item.awaiting_verdict", "success"): "INFO",
    ("queue_item.verdict_resolved", "success"): "INFO",
    ("provisioning_profile.create", "success"): "WARNING",
    ("scenario.create", "success"): "INFO",
    ("scenario.create", "failure"): "INFO",
    ("scenario.create", "denied"): "WARNING",
    ("scenario.update", "success"): "INFO",
    ("scenario.update", "failure"): "INFO",
    ("scenario.update", "denied"): "WARNING",
    ("scenario.delete", "success"): "WARNING",
    ("scenario.delete", "denied"): "WARNING",
    ("scenario.preview", "success"): "INFO",
    ("scenario_run.started", "success"): "INFO",
    ("scenario_run.waiting_for_stands", "success"): "INFO",
    ("scenario_run.stands_acquired", "success"): "INFO",
    ("scenario_run.stop_requested", "success"): "WARNING",
    ("scenario_run.succeeded", "success"): "INFO",
    ("scenario_run.failed", "failure"): "WARNING",
    ("scenario_run.stopped", "failure"): "WARNING",
    ("provisioning_profile.create", "denied"): "WARNING",
    ("provisioning_profile.update", "success"): "WARNING",
    ("provisioning_profile.update", "denied"): "WARNING",
    ("stand_setup.completed", "success"): "INFO",
    ("stand_setup.completed", "failure"): "WARNING",
    ("launch_profile.create", "success"): "WARNING",
    ("launch_profile.create", "denied"): "WARNING",
    ("launch_profile.update", "success"): "WARNING",
    ("launch_profile.update", "denied"): "WARNING",
    ("launch_profile.version_created", "success"): "WARNING",
    ("launch_profile.version_created", "denied"): "WARNING",
    ("zephyr_status_mapping.update", "success"): "INFO",
    ("zephyr_status_mapping.update", "denied"): "WARNING",
    ("zephyr_status_mapping.reset", "success"): "INFO",
    ("zephyr_status_mapping.reset", "denied"): "WARNING",
    ("queue_item.completed", "failure"): "WARNING",
    ("queue_item.interrupt_requested", "success"): "WARNING",
    ("queue_item.skipped", "success"): "WARNING",
    ("queue_item.paused", "success"): "WARNING",
    ("queue_item.resumed", "success"): "INFO",
    ("queue_item.delete", "success"): "WARNING",
    ("queue.force_takeover", "success"): "WARNING",
    ("queue.force_takeover", "failure"): "WARNING",
    ("queue.force_takeover", "denied"): "WARNING",
    ("queue.replace", "success"): "WARNING",
    ("test_stand.queue_cleared", "success"): "WARNING",
    ("test_stand.queue_retry_failed", "success"): "INFO",
    ("test_stand.queue_reordered", "success"): "INFO",
    ("test_log.rotated", "success"): "WARNING",
    ("test_run.create", "success"): "INFO",
    ("test_run.create", "denied"): "WARNING",
    ("test_run.status_changed", "success"): "INFO",
    ("stp_test_case.create", "success"): "INFO",
    ("stp_test_case.create", "failure"): "WARNING",
    ("stp_test_case.create", "denied"): "WARNING",
    ("stp_test_case.update", "success"): "INFO",
    ("stp_test_case.update", "failure"): "WARNING",
    ("stp_test_case.update", "denied"): "WARNING",
    ("stp_test_case.delete", "success"): "WARNING",
    ("stp_test_case.delete", "denied"): "WARNING",
    ("stp_test_run.generate", "success"): "INFO",
    ("stp_test_run.generate", "denied"): "WARNING",
    ("stp_cell.auto_updated", "success"): "INFO",
    ("stp_cell.manual_override", "success"): "WARNING",
    ("stp_cell.manual_override", "denied"): "WARNING",
    ("department_integration_settings.update", "success"): "INFO",
    ("department_integration_settings.update", "denied"): "WARNING",
    ("zephyr_folder.update", "success"): "INFO",
    ("zephyr_folder.update", "denied"): "WARNING",
    ("zephyr_folder.refresh", "success"): "INFO",
    ("zephyr_folder.refresh", "failure"): "WARNING",
    ("zephyr_folder.refresh", "denied"): "WARNING",
    ("run_summary_comment.posted", "success"): "INFO",
    ("run_summary_comment.posted", "failure"): "WARNING",
    ("department_report_member.create", "success"): "INFO",
    ("department_report_member.create", "denied"): "WARNING",
    ("department_report_member.update", "success"): "INFO",
    ("department_report_member.update", "denied"): "WARNING",
    ("department_report_member.delete", "success"): "WARNING",
    ("department_report_member.delete", "denied"): "WARNING",
    ("department_activity_report.generate", "success"): "INFO",
    ("department_activity_report.generate", "failure"): "WARNING",
    ("department_activity_report.generate", "denied"): "WARNING",
    ("permission.grant", "success"): "CRITICAL",
    ("permission.grant", "failure"): "WARNING",
    ("permission.grant", "denied"): "WARNING",
    ("permission.revoke", "success"): "CRITICAL",
    ("permission.revoke", "failure"): "WARNING",
    ("permission.revoke", "denied"): "WARNING",
    ("statistics_settings.update", "success"): "INFO",
    ("statistics_settings.update", "denied"): "WARNING",
    ("statistics_recalc.triggered", "success"): "INFO",
    ("statistics_recalc.triggered", "denied"): "WARNING",
    ("statistics_recalc.completed", "success"): "INFO",
    ("statistics_recalc.completed", "failure"): "WARNING",
    ("statistics_category.create", "success"): "INFO",
    ("statistics_category.create", "denied"): "WARNING",
    ("statistics_category.create", "failure"): "WARNING",
    ("statistics_category.update", "success"): "INFO",
    ("statistics_category.update", "denied"): "WARNING",
    ("statistics_category.update", "failure"): "WARNING",
    ("statistics_category.delete", "success"): "WARNING",
    ("statistics_category.delete", "denied"): "WARNING",
    ("statistics_category.delete", "failure"): "WARNING",
    ("legacy_compat.department_resolved", "success"): "INFO",
    ("legacy_compat.department_resolved", "failure"): "WARNING",
    ("compat_network.create", "success"): "WARNING",
    ("compat_network.create", "denied"): "WARNING",
    ("compat_network.create", "failure"): "WARNING",
    ("compat_network.update", "success"): "WARNING",
    ("compat_network.update", "denied"): "WARNING",
    ("compat_network.update", "failure"): "WARNING",
    ("compat_network.delete", "success"): "WARNING",
    ("compat_network.delete", "denied"): "WARNING",
    ("compat_network.delete", "failure"): "WARNING",
    ("legacy_compat_settings.update", "success"): "INFO",
    ("legacy_compat_settings.update", "denied"): "WARNING",
}


def default_severity(action: str, status: str) -> str | None:
    """Подсказка severity для пары (action, status). None — нет дефолта."""
    return _DEFAULT_SEVERITY.get((action, status))


def register_events() -> None:
    """POST полного списка событий в loging_service. Вызывается на startup.

    Не блокирует startup — при недоступности loging_service логируем WARNING.
    """
    settings = get_settings()
    logging_url = getattr(settings, "logging_service_url", None)
    api_key = getattr(settings, "logging_service_api_key", None)
    if not logging_url or not api_key:
        logger.debug("audit: skipping event registration — LOGGING_SERVICE_URL not configured")
        return
    try:
        resp = httpx.post(
            f"{logging_url}/api/logging/v1/services/{_SERVICE_NAME}/events",
            json={"events": SERVICE_EVENTS},
            headers={**bearer_header(api_key), "X-Service-Identity": "testing_service"},
            timeout=2.0,
        )
        if resp.status_code == 200:
            data = resp.json()
            logger.info(
                "audit: registered %d events (added=%d updated=%d)",
                data.get("total"), data.get("added"), data.get("updated"),
            )
        else:
            logger.warning("audit: event registration failed: %s %s", resp.status_code, resp.text)
    except Exception as exc:  # noqa: BLE001 — best-effort
        logger.warning("audit: event registration error: %s", exc)
