- name: Configure browsers
  become: yes
  vars:
    web_server: >-
      http://{{ hostvars[groups.web_servers.0].domain_name if not server.apache_postgres_together else
      hostvars[groups.databases.0].domain_name }}.{{ astra_domain }}
    web_load_balancer: '{% if not (groups.load_balancers_web|length) %}""{% else %}{{ hostvars[groups.load_balancers_web.0].domain_name }}.{{ astra_domain }}{% endif %}'
    url: '{{ web_load_balancer if server.apache.load_balancing.enabled else web_server }}'

  block:
    - name: Configure Firefox for all domain users (pass Kerberos ticket)
      copy:
        src: config-firefox.sh
        dest: /usr/share/fly-wm/config/autostart/config-firefox.sh
        mode: +x

    - name: Set default page to contrprimer in Firefox
      lineinfile:
        path: /etc/firefox/syspref.js
        regexp: '(.*)browser.startup.homepage'
        line: >-
          pref("browser.startup.homepage", "{{ url }}");

    - name: Configure Chromium's policy (pass Kerberos ticket and set default page to contrprimer)
      blockinfile:
        path: /etc/chromium/policies/managed/contrprimer.json
        create: yes
        marker: '{mark}'
        marker_begin: '{'
        marker_end: '}'
        block: |-
            "AuthServerWhitelist": ".{{ astra_domain }}",
            "AuthNegotiateDelegateWhitelist": ".{{ astra_domain }}",
            "RestoreOnStartup": 4,
            "RestoreOnStartupURLs": ["{{ url }}"],
            "HomepageLocation": "{{ url }}"
