- name: Setup client
  become: yes
  block:
    - name: Check whether machine has GUI
      stat:
        path: /etc/X11/fly-dm
      register: fly_dm

    - block:
        - name: Install necessary components
          apt:
            name:
              - firefox
              - chromium
              - libreoffice
          register: result
          until: result is not failed

        - name: Configure browsers
          import_tasks: configure_browsers.yml
      when: fly_dm.stat.exists

    - name: Wait until domain controller is ready
      vars:
        signal: domain
      import_tasks: '{{ playbook_dir }}/tasks/wait_for_domain.yml'

    - name: Setup freeipa client
      include_role:
        name: domain_client

    - name: Reboot
      reboot:
        post_reboot_delay: 5
      when: restart_domain_client is defined

- name: Installation and configuration of the RDP server
  become: yes
  become_user: root
  block:
    - name: Install RDP server
      apt:
        name:
          - xrdp
          - xorgxrdp
      register: result
      until: result is not failed

    - name: Allow access to RDP
      ufw:
        rule: allow
        port: '3389'
        proto: tcp

    - name: Enable and start RDP server
      ansible.builtin.systemd:
        name: xrdp
        state: started
        enabled: yes
  when: fly_dm.stat.exists and client.RDP.enabled