"""add_department_docker_registry

Revision ID: a36352b55ca0
Revises: 88515adafb2e
Create Date: 2026-04-18 17:33:54.215205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a36352b55ca0'
down_revision: Union[str, None] = '88515adafb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_docker_registry',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('pull_policy', sa.String(length=32), nullable=False),
    sa.Column('pull_user_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('push_user_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', name='uq_dept_docker_registry')
    )
    op.create_index(op.f('ix_department_docker_registry_department_id'), 'department_docker_registry', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_docker_registry_department_id'), table_name='department_docker_registry')
    op.drop_table('department_docker_registry')
    # ### end Alembic commands ###
