- name: Check vm exists
  shell:
    cmd: vboxmanage list vms | grep "{{ hostvars[host].vm_name | regex_escape('posix_basic') }}"
  changed_when: false
  failed_when: false
  register: exists

- name: Save results
  set_fact:
    vbox_vm_exist: "{{ dict(vbox_vm_exist | default({})) | combine({host: exists.rc == 0}) }}"