[metadata]
# При выпуски в релиз версия меняется автоматически на ту что была установлена в коммите
name = allta


version = 1.0.17
description = Модуль содержит в себе реализацию классов для упрощения написания stress тестов для ОС Astra Linux
long_description = file: README.md
long_description_content_type = text/markdown
author = team13

[options]
packages = find:
include_package_data = true

[devpi:upload]
with_docs = 1
sdist = 1
wheel = 1



[options.package_data]
allta = **/*.sh