---
- name: Main playbook STAND2
  hosts: "{{ HOST }}"
  vars:
    ASTRA_VERSION:  "1.7.3"

  tasks:   

  - include: ../tasks/check_astra_verison.yml

- include: ./syslog-ng/syslog-ng.yml
- include: ./file_system/ext4.yml
- include: ./file_system/xfs.yml
- include: ./file_system/ntfs.yml
