

stands_ip = {
    'stand1':'10.177.103.201',
    'stand2':'10.177.103.202',
    'stand3':'10.177.103.203',
    'stand4':'10.177.103.204',
    'stand10':'10.177.102.249', #KD
    'stand11':'10.177.102.200', #фронт бреста
    'stand12':'10.177.102.233'  #сервер для нагрузки
}


modes = {
    'orel':'0',
    'voronezh':'1',
    'smolensk':'2',
}

parent_page_list = {
    'debian10':{'postgresql':'Debian ⬝ PostgreSQL',
             },
    'debian10-5.15':{'postgresql':'Debian ⬝ PostgreSQL',
             },
    'debian11-6.1':{'postgresql':'Debian ⬝ PostgreSQL',
             },
    'altlinux-5.10':{'postgresql':'Debian ⬝ PostgreSQL',
             },
    '1.7.5':{'postgresql':'1.7.5 ⬝ PostgreSQL',
             'postgresql-sm':'1.7.5 ⬝ PostgreSQL',
             'postgresql-aud-off':'1.7.5 ⬝ PostgreSQL',
             'XFS':'1.7.5 ⬝ Файловые системы',
             'EXT4':'1.7.5 ⬝ Файловые системы',
             'EXT4 parsec':'1.7.5 ⬝ Файловые системы',
             'NTFS':'1.7.5 ⬝ Файловые системы',
             'auditd-p':'1.7.5 ⬝ Системные службы',
             'auditd-f':'1.7.5 ⬝ Системные службы',
             'auditd-u':'1.7.5 ⬝ Системные службы',
             'syslog-ng':'1.7.5 ⬝ Системные службы',
             'RAM-overflow':'1.7.5 ⬝ Системные службы',
             'SD-overflow':'1.7.5 ⬝ Системные службы',
             'unix':'1.7.5 ⬝ UnixBench'
             
            },
    '1.7.4.UU.1':{'postgresql':'1.7.4.UU.1 ⬝ PostgreSQL',
                  'postgresql-sm':'1.7.4.UU.1 ⬝ PostgreSQL',
                  'postgresql-aud-off':'1.7.4.UU.1 ⬝ PostgreSQL',
                  'XFS':'1.7.4.UU.1 ⬝ Файловые системы',
                  'NTFS':'1.7.4.UU.1 ⬝ Файловые системы',
                  'EXT4':'1.7.4.UU.1 ⬝ Файловые системы',
                  'EXT4 parsec':'1.7.4.UU.1 ⬝ Файловые системы',
                  'auditd-p':'1.7.4.UU.1 ⬝ Системные службы',
                  'auditd-f':'1.7.4.UU.1 ⬝ Системные службы',
                  'auditd-u':'1.7.4.UU.1 ⬝ Системные службы',
                  'syslog-ng':'1.7.4.UU.1 ⬝ Системные службы',
                  'RAM-overflow':'1.7.4.UU.1 ⬝ Системные службы',
                  'SD-overflow':'1.7.4.UU.1 ⬝ Системные службы',
                  'unix':'1.7.4.UU.1 ⬝ UnixBench'
                 },
    '1.7.4':{'postgresql':'PostgreSQL',
             'postgresql-sm':'PostgreSQL',
             'postgresql-aud-off':'PostgreSQL',
             'XFS':'Файловые системы',
             'NTFS':'Файловые системы',
             'EXT4':'Файловые системы',
             'EXT4 parsec':'Файловые системы',
             'auditd-p':'1.7.4 ⬝ Системные службы',
             'auditd-f':'1.7.4 ⬝ Системные службы',
             'auditd-u':'1.7.4 ⬝ Системные службы',
             'syslog-ng':'1.7.4 ⬝ Системные службы',
             'RAM-overflow':'1.7.4 ⬝ Системные службы',
             'SD-overflow':'1.7.4 ⬝ Системные службы',
             'unix':'UnixBench'
            },
    '1.7.2':{'postgresql':'1.7.2 ⬝ PostgreSQL',
             'postgresql-sm':'1.7.2 ⬝ PostgreSQL',
             'postgresql-aud-off':'1.7.2 ⬝ PostgreSQL',
             'auditd-p':'1.7.2 ⬝ Системные службы',
             'auditd-f':'1.7.2 ⬝ Системные службы',
             'auditd-u':'1.7.2 ⬝ Системные службы',
             'syslog-ng':'1.7.2 ⬝ Системные службы',
             'XFS':'1.7.2 ⬝ Файловые системы',
             'NTFS':'1.7.2 ⬝ Файловые системы',
             'EXT4':'1.7.2 ⬝ Файловые системы',
             'EXT4 parsec':'1.7.2 ⬝ Файловые системы',
             'RAM-overflow':'1.7.2 ⬝ Системные службы',
             'SD-overflow':'1.7.2 ⬝ Системные службы',
             'unix':'1.7.2 ⬝ UnixBench'
            },
    '1.7.3':{'postgresql':'1.7.3 ⬝ PostgreSQL',
             'postgresql-sm':'1.7.3 ⬝ PostgreSQL',
             'postgresql-aud-off':'1.7.3 ⬝ PostgreSQL',
             'auditd-p':'1.7.3 ⬝ Системные службы',
             'auditd-f':'1.7.3 ⬝ Системные службы',
             'auditd-u':'1.7.3 ⬝ Системные службы',
             'syslog-ng':'1.7.3 ⬝ Системные службы',
             'XFS':'1.7.3 ⬝ Файловые системы',
             'NTFS':'1.7.3 ⬝ Файловые системы',
             'EXT4':'1.7.3 ⬝ Файловые системы',
             'EXT4 parsec':'1.7.3 ⬝ Файловые системы',
             'RAM-overflow':'1.7.3 ⬝ Системные службы',
             'SD-overflow':'1.7.3 ⬝ Системные службы',
             'unix':'1.7.3 ⬝ UnixBench'
            },
    '1.7.3.UU.2':{'XFS':'1.7.3.UU.2 ⬝ Файловые системы',
                  'NTFS':'1.7.3.UU.2 ⬝ Файловые системы',
                  'EXT4':'1.7.3.UU.2 ⬝ Файловые системы',
                  'EXT4 parsec':'1.7.3.UU.2 ⬝ Файловые системы',
                  'postgresql':'1.7.3.UU.2 ⬝ PostgreSQL',
                  'postgresql-sm':'1.7.3.UU.2 ⬝ PostgreSQL',
                  'postgresql-aud-off':'1.7.3.UU.2 ⬝ PostgreSQL',
                  'auditd-p':'1.7.3.UU.2 ⬝ Системные службы',
                  'auditd-f':'1.7.3.UU.2 ⬝ Системные службы',
                  'auditd-u':'1.7.3.UU.2 ⬝ Системные службы',
                  'syslog-ng':'1.7.3.UU.2 ⬝ Системные службы',
                  'RAM-overflow':'1.7.3.UU.2 ⬝ Системные службы',
                  'SD-overflow':'1.7.3.UU.2 ⬝ Системные службы',
                  'unix':'1.7.3.UU.2 ⬝ UnixBench'
                 },
    '1.7.3.UU.1':{'postgresql':'1.7.3 UU1 ⬝ PostgreSQL',
                  'postgresql-sm':'1.7.3 UU1 ⬝ PostgreSQL',
                  'postgresql-aud-off':'1.7.3 UU1 ⬝ PostgreSQL',
                  'XFS':'1.7.3 UU1 ⬝ Файловые системы',
                  'NTFS':'1.7.3 UU1 ⬝ Файловые системы',
                  'EXT4':'1.7.3 UU1 ⬝ Файловые системы',
                  'EXT4 parsec':'1.7.3 UU1 ⬝ Файловые системы',
                  'auditd-p':'1.7.3 UU1 ⬝ Системные службы',
                  'auditd-f':'1.7.3 UU1 ⬝ Системные службы',
                  'auditd-u':'1.7.3 UU1 ⬝ Системные службы',
                  'syslog-ng':'1.7.3 UU1 ⬝ Системные службы',
                  'RAM-overflow':'1.7.3 UU1 ⬝ Системные службы',
                  'SD-overflow':'1.7.3 UU1 ⬝ Системные службы',
                  'unix':'1.7.3.UU.1 ⬝ UnixBench'
                 },
    '1.7.1':{'postgresql':'1.7.1 ⬝ PostgreSQL',
             'postgresql-sm':'1.7.1 ⬝ PostgreSQL',
             'postgresql-aud-off':'1.7.1 ⬝ PostgreSQL',
             'XFS':'1.7.1 ⬝ Файловые системы',
             'NTFS':'1.7.1 ⬝ Файловые системы',
             'EXT4':'1.7.1 ⬝ Файловые системы',
             'EXT4 parsec':'1.7.1 ⬝ Файловые системы',
             'syslog-ng':'Системные службы',
             'auditd-p':'Системные службы',
             'auditd-f':'Системные службы',
             'auditd-u':'Системные службы',
             'RAM-overflow':'Системные службы',
             'SD-overflow':'Системные службы',
             'unix':'1.7.1 ⬝ UnixBench'
            }
}

branches = {
    'file system benchmark. EXT4':'file_systems',
    'file system benchmark. XFS':'file_systems',
    'postgresql benchmark':'postgresql',
    'postgresql benchmark smol':'postgresql',
    'postgresql benchmark audit-off':'postgresql',
    'file system benchmark. OCFS2':'file_systems',
    'file system benchmark. NTFS':'file_systems',
    'file system benchmark. EXT3':'file_systems',
    'file system benchmark. EXT2':'file_systems',
    'file system benchmark. Fat32':'file_systems',
    'file system benchmark. EXT4 parsec':'file_systems',
    'file system benchmark. OCFS2 parsec':'file_systems',
    'auditd benchmark. psaud':'auditd',
    'auditd benchmark. fileaud':'auditd',
    'auditd benchmark. useraud':'auditd',
    'syslog-ng benchmark':'syslog_ng',
    'linux_system_benchmark. UnixBench':'linux_system',
    'ram overflow':'overflow',
    'storage drive overflow':'overflow'
}


cycle_tree_index = {
    'altlinux-5.10':'2982',
    'debian10':'2967',
    'debian10-5.15':'2974',
    'debian11-6.1':'2977',
    '1.7.5':'3032',
    '1.7.4':'2773',
    '1.7.3':'2774',
    '1.7.3.UU.1':'2745',
    '1.7.3.UU.2':'2808',
    '1.7.4.UU.1':'2936',
    '1.7.2':'2937',
    '1.7.1':'2947'
}

tests = {
    'file system benchmark. EXT4':'EXT4',
    'file system benchmark. XFS':'XFS',
    'postgresql benchmark':'postgresql',
    'postgresql benchmark smol':'postgresql-sm',
    'postgresql benchmark audit-off':'postgresql-aud-off',
    'file system benchmark. OCFS2':'OCFS2',
    'file system benchmark. NTFS':'NTFS',
    'file system benchmark. EXT3':'EXT3',
    'file system benchmark. EXT2':'EXT2',
    'file system benchmark. Fat32':'Fat32',
    'file system benchmark. EXT4 parsec':'EXT4 parsec',
    'file system benchmark. OCFS2 parsec':'OCFS2 parsec',
    'auditd benchmark. psaud':'auditd-p',
    'auditd benchmark. fileaud':'auditd-f',
    'auditd benchmark. useraud':'auditd-u',
    'syslog-ng benchmark':'syslog-ng',
    'linux_system_benchmark. UnixBench':'unix',
    'storage drive overflow':'SD-overflow',
    'ram overflow':'RAM-overflow'
}

psyc = {
        'host':'127.0.0.1',
        'database':'bendiks',
        'user':'postgres',
        'password':'1'
}            