FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y gcc build-essential && \
    apt-get clean

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Запуск Celery worker
CMD ["celery", "-A", "celery_worker.celery_app:celery_app", "worker", "--loglevel=info"]
