- name: Configure DNS settings
  become: yes
  block:
    - name: Install resolvconf
      apt:
        name: resolvconf
      register: result
      until: result is not failed

    - name: Configure resolvconf settings
      lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        regexp: "^nameserver "
        line: nameserver {{ hostvars.domain.ansible_host }}

    - name: Enable resolvconf service
      systemd:
        name: resolvconf
        state: restarted
        enabled: yes