- name: Check load balancers status
  hosts:  load_balancers_db
  vars_files: ../../../vars.yml
  gather_facts: no
  tasks:
    - name: Install python module
      become: yes
      run_once: yes
      apt:
        name: python3-pexpect

    - name: Gather info
      setup:
        gather_subset: '!all,!min,all_ipv4_addresses'

    - name: Service status
      service:
        name: pgpool2
      register: pgpool2

    - name: Show info
      debug:
        var: ansible_all_ipv4_addresses
    - debug:
        msg: >-
          State: {{ pgpool2.status.SubState }}.
          {{ 'Started: {}'.format(pgpool2.status.StateChangeTimestamp) if pgpool2.status.SubState == 'running' else '' }}

    - run_once: yes
      block:
        - name: Watchdog status
          ignore_errors: yes
          expect:
            command: /usr/sbin/pcp_watchdog_info -v -U {{ domain.admin }} -h {{ virtual_domain_name }}.{{ astra_domain }}
            responses:
              'Password:': '{{ domain.admin_password }}'
              'Пароль:': '{{ domain.admin_password }}'
          register: watchdog
          changed_when: false
        - debug:
            var: watchdog.stdout

    - run_once: yes
      block:
        - name: Database nodes status
          expect:
            command: /usr/sbin/pcp_node_info -v -U {{ domain.admin }} -h {{ virtual_domain_name }}.{{ astra_domain }}
            responses:
              'Password:': '{{ domain.admin_password }}'
              'Пароль:': '{{ domain.admin_password }}'
          register: db_nodes
          changed_when: false
        - debug:
            var: db_nodes.stdout
