- name: Check load balancers status
  hosts: '{{ groups.databases.0 }}'
  vars_files: ../../../vars.yml
  gather_facts: no
  tasks:
    - set_fact:
        num: 100

    - name: Tail log
      become: yes
      become_user: postgres
#      run_once: '{{ server.pg.load_balancing.enabled }}'
      vars:
        log_dir: /var/lib/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}/pg_log
      shell: >-
        tail -n {{ num }} {{ log_dir }}/$(ls -At {{ log_dir }} | head -n 1)
      register: log

#    - run_once: '{{ server.pg.load_balancing.enabled }}'
    - debug:
        var: log.stdout_lines



#"2022-07-01 12:10:51 MSK [1283] AUDIT: SUCCESS, DISCONNECT, 10.177.124.100, \"postgres\", SU = \"postgres\" (10), CU = \"postgres\" (10)",
#"2022-07-01 12:10:52 MSK [1283] AUDIT: SUCCESS, CONNECT, 10.177.124.42, \"postgres\", SU = \"postgres\" (10), CU = \"postgres\" (10): maclabel {0,0}",
#"2022-07-01 12:10:52 MSK [1283] AUDIT: SUCCESS, DISCONNECT, 10.177.124.42, \"postgres\", SU = \"postgres\" (10), CU = \"postgres\" (10)",
#"2022-07-01 12:10:52 MSK [1283] AUDIT: SUCCESS, CONNECT, 10.177.124.100, \"contrprimer\", SU = \"admin\" (16433), CU = \"admin\" (16433): maclabel {0,0} ignore_socket_maclabel",
#"2022-07-01 12:10:53 MSK [1283] AUDIT: SUCCESS, CONNECT, 10.177.124.100, \"postgres\", SU = \"postgres\" (10), CU = \"postgres\" (10): maclabel {0,0}",
#"2022-07-01 12:10:53 MSK [1283] AUDIT: SUCCESS, DISCONNECT, 10.177.124.100, \"postgres\", SU = \"postgres\" (10), CU = \"postgres\" (10)",