- name: Check database replication status
  hosts: databases
  vars_files: ../../../vars.yml
  gather_facts: no
  tasks:
    - name: Gather info
      become: yes
      become_user: postgres
      postgresql_info:
        db: '{{ server.pg.db_name }}'
        port: '{{ server.pg.port }}'
        filter: 'replications,in_recovery'
      register: r

    - name: Show info
      debug:
        msg: >
          {{ 
             r.replications | combine(
             {'In recovery?': r.in_recovery,
              'IP': hostvars[inventory_hostname].ansible_host}
          )}}

    - name: List physical replication slots
      become: yes
      become_user: postgres
      postgresql_query:
        port: '{{ server.pg.port }}'
        db: 'postgres'
        query: SELECT * FROM pg_replication_slots;
      register: slots
    - debug:
        msg: 'slot_name: {{ item.slot_name }}, restart_lsn: {{ item.restart_lsn }}'
      loop: '{{ slots.query_result }}'
      loop_control:
        label: ''

    - name: Read postgresql.auto.conf
      become: yes
      command: |
        cat /var/lib/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}/postgresql.auto.conf
      register: auto_conf
      changed_when: false
      failed_when: false
    - debug:
        var: auto_conf.stdout

    - name: List pgdata
      become: yes
      shell: |
        ls /var/lib/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }} | grep standby
      register: pgdata
      changed_when: false
      failed_when: false
    - debug:
        var: pgdata.stdout