#!/bin/sh
set -eu

KEY_DIR="${REGISTRY_KEYS_DIR:-/registry-keys}"
KEY_FILE="${REGISTRY_KEY_FILE:-$KEY_DIR/registry_signing.key}"
CERT_FILE="${REGISTRY_CERT_FILE:-$KEY_DIR/auth-registry.crt}"
CERT_SUBJECT="${REGISTRY_CERT_SUBJECT:-/CN=allta.devos.astralinux.ru}"
CERT_DAYS="${REGISTRY_CERT_DAYS:-3650}"
OAUTH_SECRETS_DIR="${OAUTH_CLIENT_SECRETS_DIR:-$KEY_DIR/oauth_clients}"
OAUTH_CLIENT_IDS="allta-redis allta-docs allta-flower allta-docker-ui allta-devpi allta-portainer"
OAUTH_SECRETS_ENV_FILE="${OAUTH_SECRETS_ENV_FILE:-$OAUTH_SECRETS_DIR/clients.env}"

mkdir -p "$KEY_DIR"
mkdir -p "$OAUTH_SECRETS_DIR"

if [ ! -s "$KEY_FILE" ]; then
  echo "[allta-auth-init] Generating private key: $KEY_FILE"
  openssl genrsa -out "$KEY_FILE" 4096
else
  echo "[allta-auth-init] Private key already exists: $KEY_FILE"
fi

if [ ! -s "$CERT_FILE" ]; then
  echo "[allta-auth-init] Generating self-signed certificate: $CERT_FILE"
  openssl req -new -x509 \
    -key "$KEY_FILE" \
    -out "$CERT_FILE" \
    -days "$CERT_DAYS" \
    -subj "$CERT_SUBJECT"
else
  echo "[allta-auth-init] Certificate already exists: $CERT_FILE"
fi

chmod 600 "$KEY_FILE"
chmod 644 "$CERT_FILE"

for client_id in $OAUTH_CLIENT_IDS; do
  secret_file="$OAUTH_SECRETS_DIR/${client_id}.secret"
  if [ ! -s "$secret_file" ]; then
    echo "[allta-auth-init] Generating OAuth secret: $secret_file"
    openssl rand -hex 32 > "$secret_file"
  else
    echo "[allta-auth-init] OAuth secret already exists: $secret_file"
  fi
  chmod 600 "$secret_file"

  cookie_secret_file="$OAUTH_SECRETS_DIR/${client_id}.cookie_secret"
  if [ ! -s "$cookie_secret_file" ]; then
    echo "[allta-auth-init] Generating OAuth2-Proxy cookie secret: $cookie_secret_file"
    openssl rand -base64 32 | tr -d '\n' > "$cookie_secret_file"
  else
    echo "[allta-auth-init] OAuth2-Proxy cookie secret already exists: $cookie_secret_file"
  fi
  chmod 600 "$cookie_secret_file"
done

# Convenience env file for mounting into other containers (read-only).
{
  echo "# generated by allta-auth-init"
  for client_id in $OAUTH_CLIENT_IDS; do
    env_name=$(echo "$client_id" | tr '[:lower:]-.' '[:upper:]__')
    client_secret=$(cat "$OAUTH_SECRETS_DIR/${client_id}.secret")
    cookie_secret=$(cat "$OAUTH_SECRETS_DIR/${client_id}.cookie_secret")
    echo "ALLTA_OAUTH_CLIENT_${env_name}_ID=${client_id}"
    echo "ALLTA_OAUTH_CLIENT_${env_name}_SECRET=${client_secret}"
    echo "ALLTA_OAUTH_CLIENT_${env_name}_COOKIE_SECRET=${cookie_secret}"
  done
} > "$OAUTH_SECRETS_ENV_FILE"
chmod 644 "$OAUTH_SECRETS_ENV_FILE"

echo "[allta-auth-init] Done."
