version: '3.8'
services:
  #  NGINX
  authservice-nginx:
    build:
      context: ./allta_nginx
      dockerfile: Dockerfile.allta_nginx
    image: authservice-auth-nginx:latest
    container_name: authservice-auth-nginx
    ports:
      - "21500:80"
    networks:
      authservice_network:
    depends_on:
      authservice-auth-api:
        condition: service_healthy
      authservice-config-api:
        condition: service_healthy
      docs-api-vm-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:80/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: always

  # AUTH-API
  authservice-auth-api:
    build:
      context: ../backend/allta_auth_api
      dockerfile: ../../docker_auth/allta_auth_api/allta_auth_api/Dockerfile.auth_api
    image: authservice-auth-api
    container_name: authservice-auth_api
    restart: always
    env_file:
      - $CRED_PATH/env.authservice_auth_api
    depends_on:
      authservice-auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/auth/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - authservice_network
      - authservice_auth_api     

  authservice-auth-db:
    build:
      context: ./allta_auth_api/allta_auth_db
      dockerfile: Dockerfile.allta_auth_db
    image: authservice-auth-db:latest
    container_name: authservice-auth_db
    restart: always
    env_file:
      - $CRED_PATH/env.authservice_auth_db
    volumes:
      - allta_auth_db_data:/var/lib/postgresql/data        
    networks:
      - authservice_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  authservice-config-api:
    build:
      context: ../backend/allta_config_api
      dockerfile: ../../docker_auth/allta_config_api/Dockerfile.allta_config_api
    image: authservice-config-api
    container_name: authservice-config_api
    restart: always
    env_file:
      - $CRED_PATH/env.authservice_config_api
    depends_on:
      authservice-auth-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/config/health"]
      interval: 10s
      timeout: 5s
      retries: 5              
    networks:
      - authservice_network
    volumes:
      - allta_config_data:/data
      - ${CONFIG_API_TOKENS_PATH}:/cred/tokens.json:ro

  docs-api-vm-auth:
    build:
      context: ./allta_swagger
      dockerfile: Dockerfile.allta_swagger
    image: docs-api-vm-auth:latest
    container_name: docs_api_vm_auth
    restart: always
    networks:
      authservice_network:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 3     

volumes:
  # AUTH API
  allta_auth_db_data:
    driver: local
    driver_opts:
      type: none
      device: ${AUTH_DB_PATH}
      o: bind   
  allta_config_data:
    driver: local
    driver_opts:
      type: none
      device: ${CONFIG_API_DATA_PATH}
      o: bind      

networks:

  authservice_network:
    driver: bridge

  # AUTH API
  authservice_auth_api:
    driver: bridge
