    # ——— Swagger UI документация ———
    location /api/docs/ {
        proxy_pass http://allta-swagger_upstream/;
        
        # Для корректной работы Swagger UI с BASE_URL=/api/docs
        rewrite ^/api/docs/(.*)$ /$1 break;
        
        # Переписываем URL в ответах Swagger UI
        sub_filter 'href="/' 'href="/api/docs/';
        sub_filter 'src="/' 'src="/api/docs/';
        sub_filter 'url:"/' 'url:"/api/docs/';
        sub_filter_once off;
    }