Vagrant.configure("2") do |config|
  config.vm.box = ENV['UPDATE']
  config.vm.box_url = ENV['BOX_URL']
    
  vms = [
    { :name => "virtual-station1", :hostname => "virtual-station1.allta.nt", :args => "virtual-station1", :cpus => "16", :memory => "131072", :ip => "10.177.103.101" },
    { :name => "virtual-station2", :hostname => "virtual-station2.allta.nt", :args => "virtual-station2", :cpus => "16", :memory => "131072", :ip => "10.177.103.102" },
    { :name => "virtual-station3", :hostname => "virtual-station3.allta.nt", :args => "virtual-station3", :cpus => "16", :memory => "131072", :ip => "10.177.103.103" },
    { :name => "virtual-station4", :hostname => "virtual-station4.allta.nt", :args => "virtual-station4", :cpus => "16", :memory => "131072", :ip => "10.177.103.104" }
  ]

  vms.each do |vm|
    if ENV['VM_NAME'] == vm[:name] or ENV['VM_NAME'].nil?
      config.vm.define vm[:name] do |machine|
        machine.vm.hostname = vm[:hostname]
        #machine.vm.network "public_network", ip: vm[:ip]
        machine.vm.provider "virtualbox" do |vb|
          vb.check_guest_additions = false
          vb.name = vm[:name]
          vb.memory = vm[:memory]
          vb.cpus = vm[:cpus]
          vb.customize ["modifyvm", :id, "--usb", "off"]
          vb.customize ["modifyvm", :id, "--usbehci", "off"]

          #Add new storage
          unless File.exist?("/root/VirtualBox VMs/#{vm[:name]}/#{vm[:name]}_disk.vdi")
            ctrl_type = ENV['RC'].nil? || ENV['RC'].start_with?('1.8') ? "sas" : "sata"
            ctrl_name = "#{ctrl_type.upcase} Controller #{vm[:name]}"
          
            vb.customize ['createhd', '--filename', "./#{vm[:name]}_disk.vdi", '--size', 131072 ]
            vb.customize ["storagectl", :id, "--name", ctrl_name, "--add", ctrl_type, '--portcount', 1]
            vb.customize ['storageattach', :id,  '--storagectl', ctrl_name, '--port', 0, '--device', 0, '--type', 'hdd', '--medium', "./#{vm[:name]}_disk.vdi"]
          end
        end

        machine.vm.provision "shell", path:"provision/env_provision.sh", args: [vm[:args], ENV['KERNEL'], ENV['RC']]
      end
    end
  end
end
