cluster:
        node_count = 2
        name = ocfs2

node:
        number = 0
        cluster = ocfs2
        ip_port = 7777
        ip_address = 10.0.0.25
        name = suac.rtfm.rbt

node:
        number = 1
        cluster = ocfs2
        ip_port = 7777
        ip_address = 10.0.0.22
        name = sufs.rtfm.rbt

