#!/bin/bash

set -vx

sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install htop -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install ssh git resolvconf sysstat -y
sudo timedatectl set-ntp true

iface=`ip a | grep '2: ' | awk '{print$2}' | tr -d ':' | head -n 1`

ip=$1
dns1=10.177.180.246 
dns2=10.177.128.198
gateway="10.177.103.254"

cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

auto $iface
iface $iface inet static
        address $ip
        netmask 255.255.255.0
        gateway $gateway
        dns-nameservers $dns1 $dns2
EOF

cat << EOF > /etc/resolv.conf
# Generated by Allta-vm
domain astralinux.ru
search astralinux.ru
nameserver $dns1
nameserver $dns2
EOF

# disable Network Manager
for svc in NetworkManager network-manager; do
  if systemctl list-unit-files --type=service | awk '{print $1}' | grep -qx "${svc}.service"; then
    sudo systemctl disable "${svc}.service" || true
  fi
done

sudo systemctl restart networking
nmcli connection show

echo "u  ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/u
echo "u  ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

ip a

wget ftp://10.177.103.10/allta*.deb
sudo dpkg -i allta*.deb
rm allta*.deb


# auto eth0
# iface eth0 inet static
#         address 10.177.103.101
#         netmask 255.255.255.0
#         gateway 10.177.103.254
#         dns-nameserver 10.177.128.198

# dns-nameservers 10.177.128.198