- name: Get info about internet network interfaces
  setup:
    gather_subset: '!all,!min,all_ipv4_addresses'

- name: Set config values
  set_fact:
    pg_conf_path: /etc/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}
    pg_data_path: /var/lib/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}
    replication_conf:
      # Primary
      - ['max_wal_senders', '{{ server.pg.replication.max_num_replicas }}']
      - ['max_replication_slots', '{{ server.pg.replication.max_num_replicas }}']
      #- ['wal_keep_size', '{{ server.pg.replication.wal_keep_size }}']  # TODO: maybe remove later (because of replication slots)
      # Standby
      - ['hot_standby', 'on']
      #- ['promote_trigger_file', 'failover']
      # Other
      - ['wal_level', 'replica']
      #- ['recovery_target_timeline', 'latest']
    contrprimer_conf:
      - ['listen_addresses', "'*'"]
      - ['krb_server_keyfile', "'/etc/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}/krb5.keytab'"]
      - ['autovacuum', 'on']
      # https://www.pgpool.net/pipermail/pgpool-general/2020-April/007022.html
      - ['cluster_name', "'{{ hostvars[inventory_hostname].domain_name }}_contrprimer'"]
    astra_conf:
      - ['ac_ignore_socket_maclabel', 'false']
    pg_hba_conf:
      - ['all', 'all', '0.0.0.0/0', 'md5', 'absent']
      - ['all', 'all', '{{ ansible_all_ipv4_addresses | first }}/24', 'gss', 'present',
         'include_realm=0 krb_realm={{ astra_domain | upper }}']

- name: Configure postgresql.conf
  lineinfile:
    path: '{{ pg_conf_path }}/postgresql.conf'
    regexp: '^{{ item.0 }}'
    line: '{{ item.0 }} = {{ item.1 }}'
    insertafter: '^#.*{{ item.0 }}.*\n'
    firstmatch: yes
    state: >-
      {{ "absent" if debian_linux and item in astra_conf
          else "present" if server.pg.replication.enabled
          else "absent" if item in replication_conf
          else "present" }}
  loop: '{{ contrprimer_conf + astra_conf + replication_conf }}'

- name: Configure pg_hba.conf
  become: yes
  become_user: postgres
  postgresql_pg_hba:
    dest: '{{ pg_conf_path }}/pg_hba.conf'
    contype: host
    databases: '{{ item.0 }}'
    users: '{{ item.1 }}'
    source: '{{ item.2 }}'
    method: '{{ item.3 }}'
    options: '{{ item.5 if item|length > 5 else "" }}'
    state: '{{ item.4 }}'
  loop: '{{ pg_hba_conf }}'

- name: Configure pg_hba.conf [replication]
  lineinfile:
    path: '{{ pg_conf_path }}/pg_hba.conf'
    line: 'host replication {{ server.pg.replication.user }} {{ hostvars[item].ansible_host }}/32 trust'
    state: '{{ "present" if server.pg.replication.enabled else "absent" }}'
    insertbefore: '.*gss.*$'
  loop: '{{ groups.databases }}'

- name: Configure pg_hba.conf [load_balancing] (pgpool nodes)
  lineinfile:
    path: '{{ pg_conf_path }}/pg_hba.conf'
    line: 'host all all {{ hostvars[item].ansible_host }}/32 trust'
    state: '{{ "present" if server.pg.load_balancing.enabled else "absent" }}'
    insertbefore: '.*gss.*$'
  loop: '{{ groups.load_balancers_db }}'

- name: Configure pg_hba.conf [load_balancing] (virtual ip)
  lineinfile:
    path: '{{ pg_conf_path }}/pg_hba.conf'
    line: 'host all all {{ hostvars[groups.load_balancers_db.0].delegate_ip }}/32 trust'
    state: '{{ "present" if server.pg.load_balancing.enabled else "absent" }}'
    insertbefore: '.*gss.*$'
  when: 'groups.load_balancers_db | length'

- name: Remove standby.signal
  file:
    path: '{{ pg_data_path + "/standby.signal" }}'
    state: absent
  when: not server.pg.replication.enabled

# - name: Create users
#   become: yes
#   become_user: postgres
#   vars:
#     users: "{{ [domain.user_template] | product(range(domain.num_of_users)) | map('join') }}"
#   postgresql_user:
#     port: '{{ server.pg.port }}'
#     name: '{{ item }}'
#     role_attr_flags: LOGIN
#   loop: '{{ [domain.admin] + users }}'
#   when: inventory_hostname == groups.databases.0 or not server.pg.replication.enabled

- name: Create users
  become: yes
  become_user: postgres
  vars:
    users: "{{ [domain.user_template] | product(range(domain.num_of_users)) | map('join') }}"
  tasks:
    - name: Create PostgreSQL user
      postgresql_user:
        name: '{{ item }}'
        role_attr_flags: LOGIN
        port: '{{ server.pg.port }}'
      loop: '{{ [domain.admin] + users }}'
      when: inventory_hostname == groups.databases.0 or not server.pg.replication.enabled
      register: user_creation_result

    - name: Verify PostgreSQL user creation
      postgresql_info:
        db: postgres
        query: "SELECT 1 FROM pg_roles WHERE rolname='{{ item }}';"
        port: '{{ server.pg.port }}'
      loop: '{{ [domain.admin] + users }}'
      register: user_verification_result
      when: user_creation_result is changed

    - name: Fail if user not created
      fail:
        msg: "User {{ item.item }} was not successfully created."
      loop: '{{ user_verification_result.results }}'
      when: item.queries[0] is not defined

- name: Load balancing
  block:
    - name: Create pgpool_recovery extension
      become: yes
      become_user: postgres
      postgresql_ext:
        port: '{{ server.pg.port }}'
        db: template1
        name: pgpool_recovery

    - name: Create online_recovery and pgpool_remote_start script
      template:
        src: '{{ item }}.sh.j2'
        dest: '/var/lib/postgresql/{{ server.pg.version }}/{{ server.pg.db_name }}/{{ item }}'
        owner: postgres
        group: postgres
        mode: 'u=rwx,g=rx,o=rx'
      loop: ['online_recovery', 'pgpool_remote_start']
  when: server.pg.load_balancing.enabled

- name: Replication
  block:
    - name: Clean postgresql.auto.conf
      lineinfile:
        path: '{{ pg_data_path + "/postgresql.auto.conf" }}'
        regexp: '.*{{ item }}.*'
        state: absent
      loop: ['primary_conninfo', 'primary_slot_name']

    - name: Further setup replication
      vars:
        pg_data_path: '{{ pg_data_path }}'
      import_tasks: replication.yml
  when: server.pg.replication.enabled
