- block:
    - name: Get debian version
      command: |
        lsb_release -cs
      register: version
      changed_when: false

    - name: Add postgresql debian repo
      vars:
        debian_keyring: '{{ debian.pg.keyring }}'
        debian_repo: '{{ debian.pg.repo_template.format(debian.pg.repo, version.stdout) }}'
      include_tasks: '{{ playbook_dir }}/tasks/debian_repo.yml'
  when: debian_linux

- name: Custom packages
  block:
    - name: Install custom postgresql common
      vars:
        deb_name: pg_common
        deb_packages:
          - postgresql-client-common
          - postgresql-common
        deb_version: 246astra1+ci3_all
      import_tasks: '{{ playbook_dir }}/tasks/install_custom_deb.yml'

    - name: Install custom postgresql
      vars:
        deb_name: postgresql_15
        deb_packages:
          - libpgtypes3
          - libpq5
          - libecpg6
          - libecpg-compat3
          - postgresql-client-15
          - postgresql-15
        deb_version: 15.2-astra.se1_amd64
      import_tasks: '{{ playbook_dir }}/tasks/install_custom_deb.yml'

    - name: Install custom postgresql-15-pgpool2
      vars:
        deb_name: postgresql_15
        deb_packages:
          - libpgpool2
          - postgresql-15-pgpool2
      include_tasks: '{{ playbook_dir }}/tasks/install_custom_deb.yml'
      when: server.pg.load_balancing.enabled
  when: not debian_linux and server.pg.version == 15

# TODO: удалить потом установку кастомных пакетов или добавить вариативности в настройки баз данных
#- name: Install necessary components
#  apt:
#    name:
#      - postgresql-{{ server.pg.version }}
#  register: result
#  until: result is not failed
#  when: server.pg.version != 15

- name: Install necessary components
  apt:
    name:
      #- python3-psycopg2 # for 'postgresql_*' ansible modules
      - sshpass          # for online_recovery script
  register: result
  until: result is not failed