#!/bin/bash

set -vx

# install deps
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install htop -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install ssh git resolvconf sysstat -y
sudo timedatectl set-ntp true

# check ifaddr
iface=`ip a | grep '2: ' | awk '{print$2}' | tr -d ':' | head -n 1`

# network settings
ip=$1
dns1="10.177.180.246"
dns2="10.177.128.198"
gateway="10.177.103.254"

cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

auto $iface
iface $iface inet static
        address $ip
        netmask 255.255.255.0
        gateway $gateway
        dns-nameservers $dns1 $dns2
EOF

cat << EOF > /etc/resolv.conf
# Generated by NetworkManager
domain astralinux.ru
search astralinux.ru
nameserver $dns1
nameserver $dns2
EOF

# sudoers
echo "u  ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/u
echo "u  ALL=(ALL:ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

# disable Network Manager
for svc in NetworkManager network-manager; do
  if systemctl list-unit-files --type=service | awk '{print $1}' | grep -qx "${svc}.service"; then
    sudo systemctl disable "${svc}.service" || true
  fi
done

