---
- name: Rollback snapshot
  hosts: "{{ HOST }}"
  become: true

  tasks:

  # - include: ./tasks/change_to_default_kernel.yml # Функционал не протестирован. В теории должно работать

  - name: AGBACKUP RESTORE {{ HOST }}
    shell:
      cmd: "sleep 3 && yes | agbackup restore {{ SNAPSHOT }}"
    async: 1
    poll: 0

  - name: Wait reconnect {{ HOST }}
    wait_for_connection:
      delay: 10
      timeout: 300

  - name: Test Task after reconnection to {{ HOST }}
    debug:
      msg: It's okay

  - include: ./tasks/check_astra_version.yml
  
  - name: Git pull
    become: false
    shell:
      cmd: cd /home/u/git/stress_test && git pull
