all:
  hosts:
    stand1:
      ansible_host: 10.177.5.162
    stand2:
      ansible_host: 10.177.5.191
    servermiddle:
      ansible_host: 10.177.5.121
    serverhigh:
      ansible_host: 10.177.5.118

  